Repository LiskHQ/lisk-desktop, pull requests merged in 2018-10, with the labels that each got.

#1322 E2e for news - Closes 1312
  test/cypress/e2e/news.spec.js
  test/cypress/fixtures/example.json
  test/cypress/fixtures/newsfeed/tweet.json
Labels: :white_check_mark: ready

#1323 Fix strings - Closes #1320
  i18n/locales/en/common.json
  src/components/authInputs/authInputs.js
  src/components/confirmVotes/confirmVotes.js
  src/components/header/customCountDown.js
  src/components/help/help.js
  src/components/passphrase/ConfirmSecond/confirmSecond.js
  src/components/passphrase/createSecond/create.js
  src/components/passphraseSteps/index.js
  src/components/registerDelegate/steps/choose/choose.js
  src/components/registerDelegate/steps/confirm/confirm.js
  src/components/request/confirmRequest.js
  src/components/request/index.js
  src/components/request/specifyRequest.js
  src/components/setting/setting.js
  src/components/sidechains/index.js
  src/components/toolbox/buttons/css/base.css
  src/components/transactions/transactionType.js
  src/components/transactions/transactionType.test.js
  test/cypress/e2e/ex-protractor-cucumber/registerSecondPassphrase.spec.js
  test/cypress/e2e/ex-protractor-cucumber/voting.spec.js
  test/cypress/e2e/settings.spec.js
  test/integration/wallet.test.js
Labels: :white_check_mark: ready

#1327 E2E for registration - Closes #1311
  test/cypress/e2e/login.spec.js
  test/cypress/e2e/registration.spec.js
  test/cypress/e2e/utils/chooseNetwork.js
Labels: :white_check_mark: ready

#1328 E2e for following - Closes #1313
  src/components/followedAccounts/viewAccounts.js
  test/cypress/e2e/ex-protractor-cucumber/followedAccount.spec.js
  test/cypress/e2e/following.spec.js
Labels: :white_check_mark: ready

#1334 E2E for transfer - Closes #1332
  src/components/spinner/index.js
  src/components/timestamp/index.js
  src/components/transactions/transactionRow.js
  src/components/transactions/transactionType.js
  test/constants/urls.js
  test/cypress/e2e/ex-protractor-cucumber/send.spec.js
  test/cypress/e2e/login.spec.js
  test/cypress/e2e/registration.spec.js
  test/cypress/e2e/transfer.spec.js
  test/cypress/utils/chooseNetwork.js
Labels: :white_check_mark: ready

#1279 Unhandled timestamp error - Closes #1275
  src/utils/api/transactions.js
Labels: :white_check_mark: ready

#1303 Run unit and E2E tests in parallel - Closes #1139
  Jenkinsfile
Labels: :white_check_mark: ready

#1301 Use declarative syntax in Jenkinsfile - Closes #1300
  Jenkinsfile
Labels: :eye: pending review

#1338 Change reference field to multiline - Closes #1285
  src/components/sendReadable/send.js
  src/components/sendReadable/sendReadable.css
  src/components/transactions/transactionDetailView.css
  src/components/transactions/transactionDetailView.js
Labels: :white_check_mark: ready

#1341 Clean transactions after logout - Closes #1283
  src/actions/transactions.js
  src/constants/actions.js
  src/store/middlewares/account.js
  src/store/reducers/transactions.js
Labels: :white_check_mark: ready

#1342 Invalidate bad searchparams - Closes #1324
  src/components/sendWritable/send.js
Labels: :white_check_mark: ready

#1292 Fix updating balance of followed accounts - Closes #1188
  jest.config.js
  src/store/middlewares/followedAccounts.js
  src/store/middlewares/followedAccounts.test.js
Labels: :white_check_mark: ready

#1333 Fetch 101 votes - Closes #1325
  src/actions/account.js
  src/actions/search.js
  src/utils/api/delegate.js
  src/utils/api/delegate.test.js
  test/cypress/e2e/ex-protractor-cucumber/explorer.spec.js
Labels: :white_check_mark: ready

#1349 Fix votes in wallet - Closes #1325
  src/actions/account.js
  src/actions/search.js
  src/components/transactions/walletTransactions/index.test.js
  src/utils/api/delegate.js
  src/utils/api/delegate.test.js
Labels: :white_check_mark: ready

#1340 E2E for activity - Closes #1335
  src/components/sendTo/send.js
  test/constants/urls.js
  test/cypress/e2e/activity.spec.js
  test/cypress/e2e/ex-protractor-cucumber/send.spec.js
Labels: :eye: pending review

#1348 Fix jest tests to pass in Jenkins - Closes #1302
  Jenkinsfile
  config/setupJest.js
  i18n/locales/en/common.json
  jest.config.js
  src/actions/transactions.js
Labels: :white_check_mark: ready

#1346 E2E for search - Closes #1314
  src/components/sendTo/send.js
  test/constants/accounts.js
  test/cypress/e2e/ex-protractor-cucumber/explorer.spec.js
  test/cypress/e2e/search.spec.js
Labels: :white_check_mark: ready

#1356 Show delegate statistics on a delegate account - Closes #1336
  src/components/transactions/walletTransactions/index.js
  src/components/transactions/walletTransactions/walletTransactions.js
Labels: :ballot_box_with_check: pending QA

#1354 Open direct link with autologin - Closes #1339
  src/store/middlewares/peers.js
Labels: :white_check_mark: ready

#1274 Refactor api calls middleware - Closes #934
  src/actions/peers.js
  src/actions/peers.test.js
  src/store/index.js
  src/store/middlewares/index.js
  src/store/middlewares/login.js
  src/store/middlewares/login.test.js
  test/integration/accountTransactions.test.js
  test/integration/dashboard.test.js
  test/integration/login.test.js
  test/integration/register.test.js
  test/integration/registerDelegate.test.js
  test/integration/transactionID.test.js
  test/integration/voting.test.js
  test/integration/wallet.test.js
Labels: :white_check_mark: ready

#1355 Update test doc - Closes #1329
  README.md
  docs/TEST_GUIDE.md
Labels: :white_check_mark: ready

#1360 Disable concurrent builds
  Jenkinsfile
Labels: :white_check_mark: ready

#1363 Show delegate statistics - Closes #1336
  src/components/transactions/walletTransactions/index.js
Labels: :white_check_mark: ready

#1227 Update jenkins core to 1.1.0 - Closes #1202
  Jenkinsfile
  README.md
  e2e-test-setup.sh
  test/blockchain.db.gz
  test/constants/accounts.js
  test/cypress/e2e/ex-protractor-cucumber/voting.spec.js
  test/cypress/e2e/transfer.spec.js
  test/e2e-test-setup.sh
  test/e2e-transactions.sh
Labels: :white_check_mark: ready

#1367 Set parallelBuild for Xvfb plugin - Closes #1366
  Jenkinsfile
Labels: :white_check_mark: ready

#1365 Alignment of bottom sidebar navigation elements - Closes #1195
  src/components/mainMenu/mainMenu.css
  src/components/mainMenu/mainMenu.js
Labels: :white_check_mark: ready

#1381 Update blockchain snapshot - Closes #1380
  test/blockchain.db.gz
  test/constants/accounts.js
  test/cypress/e2e/login.spec.js
  test/e2e-transactions.sh
Labels: :white_check_mark: ready

#1379 Set autoDisplayName for Xvfb plugin - Closes #1378
  Jenkinsfile
Labels: :white_check_mark: ready

#1364 Styling of network switcher on Sign In - Closes #1194
  src/components/toolbox/dropdown/dropdown.css
Labels: :white_check_mark: ready

#1368 Change chart font color - Closes #1347
  src/components/dashboard/currencyGraph.js
Labels: :white_check_mark: ready

#1372 Adjust width for search input large screen breakpoint - Closes #1353
  src/components/searchBar/searchBar.css
Labels: :white_check_mark: ready

#1374 Unable to register as a delegate with an account balance of 25 - Closes #1350
  src/components/registerDelegate/steps/choose/choose.js
Labels: :white_check_mark: ready

#1390 Fix address search results when address is > 20 chars - Closes #1352
  src/utils/api/delegate.js
  src/utils/api/search.js
Labels: :ballot_box_with_check: pending QA

#1389 Report Cypress results to GitHub - Closes #1382
  Jenkinsfile
Labels: :white_check_mark: ready

#1388 Improve design bookmarks - Close #1375
  src/components/bookmark/bookmark.css
  src/components/bookmark/bookmark.js
  src/components/sendReadable/send.js
  src/components/sendReadable/sendReadable.css
Labels: :white_check_mark: ready

#1393 E2E tests for delegate registration - Closes #1370
  test/constants/urls.js
  test/cypress/e2e/delegateReg.spec.js
  test/cypress/e2e/ex-protractor-cucumber/registerDelegate.spec.js
  test/cypress/e2e/login.spec.js
  test/cypress/e2e/secondPassphraseReg.spec.js
  test/cypress/e2e/transfer.spec.js
  test/cypress/utils/enterSecondPassphrase.js
Labels: :eye: pending review

#1297 Move newsFeed API call to actions - Closes #1293
  karma.conf.js
  src/actions/liskService.js
  src/components/converter/converter.js
  src/components/converter/converter.test.js
  src/components/converter/index.js
  src/components/converter/index.test.js
  src/components/newsFeed/index.js
  src/components/newsFeed/index.test.js
  src/components/newsFeed/newsFeed.js
  src/components/newsFeed/newsFeed.test.js
  src/components/request/specifyRequest.test.js
  src/components/send/index.test.js
  src/components/sendWritable/index.test.js
  src/components/sendWritable/send.test.js
  src/constants/actions.js
  src/store/reducers/liskService.js
Labels: :white_check_mark: ready

#1392 Show the actual error in login error toast - Closes #1357
  i18n/locales/en/common.json
  src/actions/peers.js
  src/actions/peers.test.js
  test/integration/login.test.js
Labels: :white_check_mark: ready

#1399 Prevent random fail of login to custom node - Closes #1398
  src/actions/peers.js
Labels: :white_check_mark: ready

#1362 Display full voters - Closes #1344
  i18n/locales/en/common.json
  jest.config.js
  src/actions/account.js
  src/actions/search.js
  src/actions/search.test.js
  src/components/transactions/accountList.js
  src/components/transactions/delegateStatistics.css
  src/components/transactions/delegateStatistics.test.js
  src/components/transactions/explorerTransactions/explorerTransactions.js
  src/components/transactions/explorerTransactions/index.js
  src/components/transactions/transactionList.js
  src/components/transactions/transactionOverview.js
  src/components/transactions/votedDelegates.js
  src/components/transactions/votedDelegates.test.js
  src/components/transactions/walletTransactions/index.test.js
  src/store/reducers/search.js
  src/utils/api/delegate.js
  src/utils/api/delegate.test.js
  test/integration/accountTransactions.test.js
Labels: :white_check_mark: ready

#1409 Do not show balance if undefined - Closes #1391
  src/components/liskAmount/index.js
Labels: :white_check_mark: ready

#1408 Allocate random port numbers for core - Closes #1386
  Jenkinsfile
  test/cypress/e2e/delegates.spec.js
Labels: :white_check_mark: ready

#1397 Transactions to 'yourself' are all seen as "account initialization" - Closes #1281
  src/components/sendReadable/send.js
  src/components/transactions/transactionType.js
  test/cypress/e2e/transfer.spec.js
  test/integration/wallet.test.js
Labels: :white_check_mark: ready
