Repository LiskHQ/lisk-desktop, pull requests merged in 2018-05, with the labels that each got.

#778 Strip initial, traling and multiple white spaces of Passphrase - Closes #750
  src/components/passphraseInput/index.js
Labels: :eye: pending review

#747 Create common component for the logic of 1st and 2nd passphrase generation
  i18n/locales/en/common.json
  karma.conf.js
  src/components/passphrase/create/create.css
  src/components/passphrase/create/create.js
  src/components/passphrase/create/create.test.js
  src/components/passphrase/create/index.js
  src/components/passphrase/createSecond/create.js
  src/components/passphrase/createSecond/create.test.js
  src/components/passphrase/createSecond/index.js
  src/components/passphraseCreation/index.js
  src/components/send/index.js
  test/integration/register.test.js
Labels: :white_check_mark: ready

#746 Refactor search results to use redux store - Closes #744
  src/actions/account.js
  src/actions/account.test.js
  src/actions/transactions.js
  src/actions/transactions.test.js
  src/actions/voting.js
  src/actions/voting.test.js
  src/components/accountTransactions/index.js
  src/components/accountTransactions/index.test.js
  src/components/dashboard/index.js
  src/components/singleTransaction/index.js
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionDetailView.test.js
  src/components/transactions/transactionList.js
  src/components/transactions/transactionList.test.js
  src/components/transactions/transactionOverview.js
  src/constants/actions.js
  src/store/middlewares/account.js
  src/store/middlewares/index.js
  src/store/middlewares/transactions.js
  src/store/middlewares/transactions.test.js
  src/store/reducers/account.js
  src/store/reducers/transaction.js
  src/store/reducers/transactions.js
  test/integration/accountTransactions.test.js
  test/integration/dashboard.test.js
  test/integration/transactionID.test.js
  test/integration/voting.test.js
  test/integration/wallet.test.js
  test/utils/genericStepDefinition.js
  test/utils/mountHelpers.js
Labels: :eye: pending review

#781 Implement basic request LSK tab
  i18n/locales/en/common.json
  src/components/multiStep/index.js
  src/components/request/index.js
  src/components/request/request.css
  src/components/send/index.js
  src/components/sendWritable/send.js
  src/components/transferTabs/index.js
  src/components/transferTabs/tabs.css
  test/integration/wallet.test.js
Labels: :eye: pending review

#790 Add PR branch name to email notification subject when applicable - Closes #789
  Jenkinsfile
Labels: :eye: pending review

#794 Fix breaking app when removing last saved account - Closes #792
  src/utils/savedAccounts.js
  src/utils/savedAccounts.test.js
Labels: :white_check_mark: ready

#788 Add remaining request steps - Closes #782
  i18n/locales/en/common.json
  src/components/converter/index.js
  src/components/multiStep/index.js
  src/components/request/confirmRequest.js
  src/components/request/confirmRequest.test.js
  src/components/request/index.js
  src/components/request/input.css
  src/components/request/request.css
  src/components/request/specifyRequest.js
  src/components/request/specifyRequest.test.js
  src/components/send/index.js
  src/components/sendWritable/send.js
  src/components/toolbox/buttons/css/tertiaryButton.css
  src/components/toolbox/inputs/input.css
  src/utils/externalLinks.js
  test/integration/wallet.test.js
Labels: :white_check_mark: ready

#791 Fix style inconsistencies in settings - Closes #791
  src/components/setting/setting.css
Labels: :eye: pending review

#760 Setup React error boundaries to prevent one component breaking the whole app - Closes #643
  config/webpack.config.react.js
  i18n/locales/en/common.json
  karma.conf.js
  src/components/app/index.js
  src/components/customRoute/index.js
  src/components/customRoute/index.test.js
  src/components/emptyState/index.js
  src/components/errorBoundary/errorBoundary.css
  src/components/errorBoundary/index.js
  src/components/errorBoundary/index.test.js
Labels: :eye: pending review

#765 Add delegate statistics page - Closes #751
  i18n/locales/en/common.json
  karma.conf.js
  src/actions/account.js
  src/components/accountTransactions/index.js
  src/components/accountTransactions/index.test.js
  src/components/transactions/delegateStatistics.css
  src/components/transactions/delegateStatistics.js
  src/components/transactions/delegateStatistics.test.js
  src/components/transactions/transactionList.js
  src/components/transactions/transactionList.test.js
  src/components/transactions/transactionOverview.js
  src/constants/actions.js
  src/constants/transactionFilters.js
  src/store/reducers/account.js
  src/store/reducers/account.test.js
  src/utils/api/delegate.js
  src/utils/api/delegate.test.js
  test/e2e/explorer.feature
  test/e2e/step_definitions/generic.step.js
  test/integration/delegates.test.js
  test/integration/login.test.js
Labels: :eye: pending review

#815 Fix for autoupdate error - Closes #808
  app/src/modules/autoUpdater.test.js
  app/src/modules/updateModal.js
  app/src/modules/updateModal.test.js
  app/src/update.html
Labels: :eye: pending review

#814 Add price converter e2e tests - Closes #796
  src/components/converter/index.js
  src/components/converter/index.test.js
  test/e2e/send.feature
  test/e2e/step_definitions/send.step.js
Labels: :eye: pending review

#811 Fix "Download was started" typo in autoupdater - Closes #807
  app/src/modules/autoUpdater.js
  i18n/locales/en/common.json
Labels: :eye: pending review

#797 Add sign messages - Closes #457
  i18n/locales/en/common.json
  src/components/passphraseInput/passphraseInput.css
  src/components/signMessage/confirmMessage.css
  src/components/signMessage/confirmMessage.js
  src/components/signMessage/index.js
  src/components/signMessage/signMessage.css
  src/components/signMessage/signMessage.js
  src/components/signMessage/signMessage.test.js
  src/components/signMessage/signMessageInput.css
  src/components/signMessage/signMessageInput.js
  src/components/transactions/delegateStatistics.css
  src/constants/routes.js
Labels: :building_construction: in progress

#798 Fix not displaying voters and voting - Closes #793
  src/components/transactions/transactionRow.js
  src/store/reducers/transaction.js
  src/store/reducers/transaction.test.js
  test/e2e/explorer.feature
  test/e2e/step_definitions/generic.step.js
  test/e2e/step_definitions/transactions.step.js
  test/integration/accountTransactions.test.js
Labels: :eye: pending review

#787 Fix the paddings of voting confirmation in Large viewport - Closes #777
  src/components/confirmVotes/confirmVotes.css
  src/components/delegateSidebar/delegateSidebar.css
  src/components/voting/voting.css
Labels: :eye: pending review

#774 Add dedicated identity in Redux Store for search results - Closes #767
  karma.conf.js
  src/actions/account.test.js
  src/actions/search.js
  src/actions/transactions.js
  src/components/accountTransactions/index.js
  src/components/accountTransactions/index.test.js
  src/components/dashboard/index.js
  src/components/sendTo/index.js
  src/components/sendTo/sendTo.test.js
  src/components/transactions/delegateStatistics.js
  src/components/transactions/delegateStatistics.test.js
  src/components/transactions/index.js
  src/components/transactions/index.test.js
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionDetailView.test.js
  src/components/transactions/transactionList.js
  src/components/transactions/transactionOverview.js
  src/components/transactions/transactionOverview.test.js
  src/components/voting/index.test.js
  src/components/voting/voting.test.js
  src/constants/actions.js
  src/store/reducers/account.test.js
  src/store/reducers/index.js
  src/store/reducers/search.js
  test/e2e/explorer.feature
  test/e2e/send.feature
  test/integration/accountTransactions.test.js
  test/integration/dashboard.test.js
  test/integration/delegates.test.js
  test/integration/wallet.test.js
Labels: :eye: pending review

#822 Fix the issue with infinite scroll in delegates list - Closes #729
  src/components/votingListView/index.js
  src/components/votingListView/votingListView.js
  test/e2e/explorer.feature
  test/e2e/step_definitions/generic.step.js
Labels: :eye: pending review

#819 Convert settings to a page - Closes #810
  i18n/locales/en/common.json
  src/assets/images/main-menu-icons/dasboard.svg
  src/assets/images/main-menu-icons/settings.svg
  src/assets/images/main-menu-icons/wallet.svg
  src/components/app/index.js
  src/components/mainMenu/index.test.js
  src/components/mainMenu/mainMenu.js
  src/components/mainMenu/mainMenu.test.js
  src/components/menuBar/menuBar.js
  src/components/menuBar/menuBar.test.js
  src/components/onboarding/index.js
  src/components/onboarding/onboarding.test.js
  src/components/setting/setting.css
  src/components/setting/setting.js
  src/components/setting/setting.test.js
  src/constants/routes.js
  src/store/reducers/settings.js
  test/e2e/onboarding.feature
  test/integration/accountTransactions.test.js
Labels: :building_construction: in progress

#826 Better caching based on checksuming package.json - Closes #825
  Jenkinsfile
Labels: :eye: pending review

#827 Update iconfont - Closes #820
  src/assets/fonts/iconfont/icons.html
  src/assets/fonts/iconfont/icons.ttf
  src/assets/fonts/iconfont/icons.woff
  src/components/fontIcon/fontIcon.css
  src/components/voteUrlProcessor/voteUrlProcessor.css
  src/components/voteUrlProcessor/voteUrlProcessor.js
Labels: :eye: pending review

#852 Fix incorrect symbol for outgoing transactions in transaction detail - Closes #850
  src/components/singleTransaction/index.js
Labels: :eye: pending review

#838 Vendor prefixes by stylelint - Closes
  config/webpack.config.react.js
  src/components/transactions/delegateStatistics.css
  src/components/votingListView/votingHeader.css
Labels: :eye: pending review

#855 Close transaction detail on menu click - Closes #843
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionDetailView.test.js
Labels: :eye: pending review

#859 Fix liskID creator not scrollable - Closes #839
  src/components/passphrase/create/create.css
Labels: :eye: pending review

#860 Switch 1 month graph option to 2 weeks - Closes #800
  src/components/dashboard/currencyGraph.js
Labels: :eye: pending review

#836 Add new api for delegate search autocomplete - Closes #832
  src/utils/api/search.js
  src/utils/api/search.test.js
Labels: :eye: pending review

#799 Write tests for passphrase creation - Closes #771
  karma.conf.js
  src/components/passphraseCreation/index.js
  src/components/passphraseCreation/index.test.js
  src/utils/checkDevice.js
Labels: :white_check_mark: ready

#841 Redesign sidebar menu - Closes #828
  i18n/locales/en/common.json
  src/components/app/app.css
  src/components/app/variables.css
  src/components/mainMenu/mainMenu.css
  src/components/mainMenu/mainMenu.js
  src/components/mainMenu/mainMenu.test.js
  src/components/onboarding/steps.js
Labels: :eye: pending review

#861 Fix unstable e2e tests - Closes #824
  src/components/transactions/transactionDetailView.js
  test/e2e/explorer.feature
  test/e2e/registerDelegate.feature
  test/e2e/registerSecondPassphrase.feature
  test/e2e/send.feature
Labels: :eye: pending review

#821 Cache delegate names lookup in local storage - Closes #783
  src/actions/transactions.js
  src/actions/transactions.test.js
  src/actions/voting.js
  src/actions/voting.test.js
  src/components/transactions/transactionDetailView.css
  src/components/transactions/transactionDetailView.js
  src/store/reducers/transaction.js
  src/store/reducers/transaction.test.js
  src/utils/delegates.js
  src/utils/delegates.test.js
Labels: :eye: pending review

#863 Add unit tests for accountVisual - Closes #862
  karma.conf.js
  src/components/accountVisual/index.test.js
Labels: :eye: pending review
