Repository LiskHQ/lisk-desktop, pull requests merged in 2018-06, with the labels that each got.

#849 Refactor transactionDetailView - Closes #784
  i18n/locales/en/common.json
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionDetailViewField.js
  src/components/transactions/transactionDetailViewRow.js
  test/integration/transactionID.test.js
Labels: :eye: pending review

#876 Random failing e2etests due to reseting transaction filter - Closes #875
  src/components/transactions/explorerTransactions/explorerTransactions.js
  src/components/transactions/transactionOverview.js
  src/components/transactions/walletTransactions/index.js
  src/components/transactions/walletTransactions/index.test.js
  src/components/transactions/walletTransactions/walletTransactions.js
  test/e2e/registerDelegate.feature
  test/integration/wallet.test.js
Labels: :eye: pending review

#872 Prevent page-not-found after auto update on windows - Closes #870
  src/utils/externalLinks.js
Labels: :eye: pending review

#873 Fix sign message shouldn't ask for passphrase if account is unlocked - Closes #864
  src/components/signMessage/confirmMessage.js
  src/components/signMessage/signMessage.test.js
Labels: :eye: pending review

#877 Add hash to icons - Closes #871
  config/webpack.config.js
Labels: :eye: pending review

#848 Create autosuggest component for delegate search - Closes #833
  i18n/locales/en/common.json
  src/components/app/variables.css
  src/components/autoSuggest/autoSuggest.css
  src/components/autoSuggest/index.js
  src/components/autoSuggest/index.test.js
  src/components/autoSuggest/resultsList.css
  src/components/autoSuggest/resultsList.js
  src/components/autoSuggest/searchResults.mock.js
  src/constants/keyCodes.js
Labels: :eye: pending review

#884 Fix displaying statistics for non-delegate - Closes #883
  src/components/transactions/transactionOverview.js
Labels: :eye: pending review

#886 Add currency switcher to settings - Closes #845
  src/components/send/index.js
  src/components/setting/setting.js
  src/components/setting/setting.test.js
  src/components/votingListView/voteCheckbox.js
  src/constants/settings.js
Labels: :eye: pending review

#868 Provide actions reducers for autosuggest search - Closes #857
  karma.conf.js
  src/actions/search.js
  src/components/autoSuggest/index.test.js
  src/constants/actions.js
  src/store/reducers/search.js
Labels: :eye: pending review

#858 Add e2e tests for launch protocol - Closes #851
  docs/PROTOCOL_GUIDE.md
  docs/assets/network_switcher.png
  docs/assets/send.png
  docs/assets/sign_message.png
  test/e2e/login.feature
  test/e2e/send.feature
  test/e2e/signMessage.feature
  test/e2e/step_definitions/hooks.js
  test/e2e/voting.feature
Labels: :building_construction: in progress

#887 Add network switcher to settings - Closes #830
  README.md
  i18n/locales/en/common.json
  src/components/login/index.js
  src/components/login/login.js
  src/components/login/login.test.js
  src/components/mainMenu/mainMenu.js
  src/components/onboarding/index.js
  src/components/setting/setting.css
  src/components/setting/setting.js
  src/components/setting/setting.test.js
  src/constants/routes.js
  src/store/reducers/settings.js
  test/e2e/step_definitions/hooks.js
  test/integration/login.test.js
Labels: :eye: pending review

#912 Add redux logic for followed accounts - Closes #902
  src/actions/followedAccounts.js
  src/actions/followedAccounts.test.js
  src/constants/actions.js
  src/store/index.js
  src/store/middlewares/followedAccounts.js
  src/store/middlewares/followedAccounts.test.js
  src/store/middlewares/index.js
  src/store/reducers/followedAccounts.js
  src/store/reducers/followedAccounts.test.js
  src/store/reducers/index.js
  src/store/subscribers/followedAccounts.js
  src/store/subscribers/followedAccounts.test.js
  src/utils/followedAccounts.js
Labels: :white_check_mark: ready

#878 Delegate search api integrated with autosuggest - Closes #834, #835 , #865
  i18n/locales/en/common.json
  src/actions/search.js
  src/components/app/index.test.js
  src/components/autoSuggest/autoSuggest.css
  src/components/autoSuggest/index.js
  src/components/autoSuggest/index.test.js
  src/components/autoSuggest/resultsList.css
  src/components/autoSuggest/resultsList.js
  src/components/autoSuggest/searchResults.mock.js
  src/components/header/header.test.js
  src/components/header/index.test.js
  src/components/search/keyAction.js
  src/components/searchBar/index.js
  src/components/searchBar/index.test.js
  src/components/searchBar/searchBar.css
  src/store/reducers/search.js
  src/store/reducers/search.test.js
  src/utils/api/search.js
  src/utils/api/search.test.js
  test/e2e/explorer.feature
Labels: :eye: pending review

#911 Decrease likelihood of the blue line of price chart toolitp - Closes #893
  src/components/dashboard/currencyGraph.css
  src/components/dashboard/currencyGraph.js
Labels: :eye: pending review

#908 Dont allow to call API when going on Delegate statistics page - Closes #879
  src/actions/search.js
  src/actions/transactions.js
  src/components/accountTransactions/index.test.js
  src/components/fontIcon/fontIcon.css
  src/components/transactions/explorerTransactions/explorerTransactions.js
  src/components/transactions/explorerTransactions/index.js
  src/components/transactions/explorerTransactions/index.test.js
  src/components/transactions/walletTransactions/index.js
  src/components/transactions/walletTransactions/index.test.js
  src/components/transactions/walletTransactions/walletTransactions.js
  src/constants/actions.js
  src/store/reducers/filters.js
  src/store/reducers/index.js
  test/integration/accountTransactions.test.js
  test/integration/wallet.test.js
Labels: :eye: pending review

#901 Update autosuggest input placeholder with suggested results - Closes #900
  src/components/app/variables.css
  src/components/autoSuggest/autoSuggest.css
  src/components/autoSuggest/index.js
  src/components/autoSuggest/index.test.js
  src/components/searchBar/index.js
  src/components/searchBar/index.test.js
Labels: :eye: pending review

#922 Verify that passphrase used belongs to active account - Cooses #921
  src/components/signMessage/confirmMessage.js
Labels: :eye: pending review

#909 Styling of sign message - Closes #880
  i18n/locales/en/common.json
  src/components/app/variables.css
  src/components/signMessage/confirmMessage.css
  src/components/signMessage/signMessage.js
Labels: :eye: pending review

#918 Add followed accounts to dashboard - Closes #903 #890 #905
  i18n/locales/en/common.json
  src/actions/followedAccounts.js
  src/components/addressInput/addressInput.css
  src/components/addressInput/index.js
  src/components/dashboard/currencyGraph.css
  src/components/dashboard/dashboard.css
  src/components/dashboard/index.js
  src/components/followedAccounts/dashboard/addAccountID.js
  src/components/followedAccounts/dashboard/addAccountID.test.js
  src/components/followedAccounts/dashboard/addAccountTitle.js
  src/components/followedAccounts/dashboard/addAccountTitle.test.js
  src/components/followedAccounts/dashboard/followedAccounts.css
  src/components/followedAccounts/dashboard/index.js
  src/components/followedAccounts/dashboard/viewAccounts.js
  src/components/followedAccounts/dashboard/viewAccounts.test.js
  src/components/sendWritable/send.js
  src/store/middlewares/followedAccounts.js
  src/store/middlewares/followedAccounts.test.js
  src/store/reducers/followedAccounts.js
  src/store/reducers/followedAccounts.test.js
  src/store/subscribers/followedAccounts.js
  src/store/subscribers/followedAccounts.test.js
  src/utils/followedAccounts.js
  src/utils/followedAccounts.test.js
  test/integration/dashboard.test.js
Labels: :eye: pending review

#882 Refactor api calls in middlewares - Closes #770
  src/actions/account.js
  src/actions/account.test.js
  src/actions/search.js
  src/actions/transactions.js
  src/actions/transactions.test.js
  src/components/sendReadable/index.js
  src/components/transactions/explorerTransactions/index.test.js
  src/components/transactions/walletTransactions/index.test.js
  src/store/middlewares/account.js
  src/store/middlewares/account.test.js
  src/utils/api/account.js
  src/utils/api/account.test.js
  src/utils/api/search.js
  src/utils/api/transactions.js
  src/utils/api/transactions.test.js
  test/integration/wallet.test.js
Labels: :white_check_mark: ready

#910 Show recent searches in autosuggest - Closes #895
  i18n/locales/en/common.json
  src/components/autoSuggest/index.js
  src/components/autoSuggest/index.test.js
  test/e2e/explorer.feature
Labels: :eye: pending review

#885 Limit linux builds to x86_64
  Jenkinsfile
  package.json
Labels: *easy, :eye: pending review

#924 Use jenkins library - Closes #923
  Jenkinsfile
Labels: :building_construction: in progress

#930 Add followed accounts to account profile page - Closes #907
  i18n/locales/en/common.json
  src/assets/fonts/iconfont/icons.html
  src/assets/fonts/iconfont/icons.ttf
  src/assets/fonts/iconfont/icons.woff
  src/components/accountTransactions/index.test.js
  src/components/followedAccounts/accountTitleInput.js
  src/components/followedAccounts/addAccountTitle.js
  src/components/followedAccounts/addAccountTitle.test.js
  src/components/followedAccounts/titleInputForList.js
  src/components/followedAccounts/viewAccounts.js
  src/components/fontIcon/fontIcon.css
  src/components/sendTo/followAccount.css
  src/components/sendTo/followAccount.js
  src/components/sendTo/followAccount.test.js
  src/components/sendTo/index.js
  src/components/sendTo/send.js
  src/components/sendTo/sendTo.css
  src/components/sendTo/sendTo.test.js
  src/components/transactions/explorerTransactions/index.test.js
  src/components/transactions/transactionOverview.js
  src/components/transactions/transactionOverview.test.js
  src/components/transactions/transactions.css
  src/components/transactions/walletTransactions/index.test.js
  test/integration/accountTransactions.test.js
  test/integration/wallet.test.js
Labels: :eye: pending review

#935 Join two boxes in profile and delegate page
  src/components/accountTransactions/accountTransactions.css
  src/components/accountTransactions/index.js
  src/components/app/variables.css
  src/components/delegateSidebar/delegateSidebar.css
  src/components/sendTo/followAccount.css
  src/components/sendTo/sendTo.css
  src/components/transactions/explorerTransactions/explorerTransactions.js
  src/components/transactions/transactions.css
  src/components/voting/voting.css
  src/components/voting/voting.js
  src/components/votingListView/votingListView.css
Labels: :eye: pending review

#933 Add e2e tests for followed accounts - Closes #906
  src/components/sendTo/send.js
  test/e2e/explorer.feature
  test/e2e/followedAccounts.feature
Labels: :white_check_mark: ready

#919 Remove explorer and references to it in src - Closes #896
  i18n/locales/en/common.json
  src/components/app/index.test.js
  src/components/autoSuggest/index.js
  src/components/autoSuggest/resultsList.js
  src/components/box/box.css
  src/components/dialog/dialog.test.js
  src/components/header/header.js
  src/components/login/layout.css
  src/components/mainMenu/index.test.js
  src/components/mainMenu/mainMenu.js
  src/components/mainMenu/mainMenu.test.js
  src/components/onboarding/steps.js
  src/components/search/index.js
  src/components/search/index.test.js
  src/components/search/keyAction.js
  src/components/search/keyAction.test.js
  src/components/searchBar/index.js
  src/constants/routes.js
  src/utils/app.test.js
  test/e2e/explorer.feature
  test/e2e/onboarding.feature
  test/e2e/step_definitions/explorer.step.js
Labels: :eye: pending review

#954 Add network switcher missiong description - Closes #947
  i18n/locales/en/common.json
  src/components/setting/setting.css
  src/components/setting/setting.js
Labels: :white_check_mark: ready

#951 Change text in Delegate Details page - Closes #949
  i18n/locales/en/common.json
  src/components/transactions/userVotes.js
  src/components/transactions/votedDelegates.js
  src/components/transactions/walletTransactions/index.test.js
Labels: :eye: pending review

#953 Redirect to valid entity results page when no autosuggestion result used - Closes #946
  src/components/autoSuggest/index.js
  src/components/autoSuggest/index.test.js
  src/constants/search.js
Labels: :building_construction: in progress

#959 Use search value for saving into recent searches - Closes #950
  src/components/autoSuggest/autoSuggest.css
  src/components/autoSuggest/index.js
  src/components/autoSuggest/index.test.js
  src/components/autoSuggest/resultsList.js
  src/components/search/keyAction.js
  src/components/search/keyAction.test.js
Labels: :eye: pending review

#960 Autosuggest should not collide with main content on signin - Closes #958
  src/components/header/header.css
Labels: :eye: pending review

#961 Don't hide explorer elements while loading - Closes #928
  src/components/accountTransactions/index.js
  src/components/sendTo/send.js
  src/components/sendTo/sendTo.test.js
  src/components/transactions/transactionList.js
  src/components/transactions/transactionList.test.js
Labels: :eye: pending review

#970 Send features, show single Transactions migration to 1.0.0 - Closes #967
  src/actions/transactions.js
  src/store/reducers/transaction.js
  src/utils/api/search.js
  src/utils/api/transactions.js
  test/e2e/send.feature
Labels: :eye: pending review
