Repository LiskHQ/lisk-desktop, pull requests merged in 2018-11, with the labels that each got.

#1416 E2E sign message tests - Closes #1413
  test/constants/urls.js
  test/cypress/e2e/ex-protractor-cucumber/signMessage.spec.js
  test/cypress/e2e/signMessage.spec.js
Labels: :white_check_mark: ready

#1417 E2E for Tx details - Closes #1414
  src/components/timestamp/index.js
  src/components/transactions/amount.js
  src/components/transactions/amount.test.js
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionDetailViewField.js
  test/cypress/e2e/delegateReg.spec.js
  test/cypress/e2e/secondPassphraseReg.spec.js
  test/cypress/e2e/transfer.spec.js
  test/cypress/e2e/txDetails.spec.js
  test/integration/transactionID.test.js
Labels: :white_check_mark: ready

#1426 E2E Bookmarks test - Closes #1415
  test/cypress/e2e/bookmarks.js
Labels: :white_check_mark: ready

#1321 Implement show ledger accounts
  .babelrc
  app/src/ledger.js
  app/src/main.js
  config/webpack.config.js
  i18n/locales/en/common.json
  karma.conf.js
  package-lock.json
  package.json
  src/actions/peers.js
  src/assets/images/ledger-nano-s.png
  src/components/formattedNumber/index.js
  src/components/ledger/accountCard.css
  src/components/ledger/accountCard.js
  src/components/ledger/addAccountCard.js
  src/components/ledger/index.js
  src/components/ledger/ledgerLogin.css
  src/components/ledger/ledgerLogin.js
  src/components/ledger/unlockWallet.css
  src/components/ledger/unlockWallet.js
  src/components/login/index.js
  src/components/login/index.test.js
  src/components/login/login.css
  src/components/login/login.js
  src/components/transactions/transactionList.js
  src/constants/hwConstants.js
  src/store/middlewares/login.js
  src/store/reducers/settings.js
  src/utils/api/ledger.js
  src/utils/ledger.js
  src/utils/rawTransactionWrapper.js
  src/utils/to.js
Labels: :white_check_mark: ready

#1377 Set max amount - Closes #1234
  i18n/locales/en/common.json
  src/components/converter/converter.js
  src/components/converter/converter.test.js
  src/components/sendWritable/send.js
  src/components/sendWritable/send.test.js
  src/components/sendWritable/sendWritable.css
  src/components/toolbox/inputs/input.css
Labels: :white_check_mark: ready

#1450 Fix Jenkins build by disabling minification - Mitigates #1439
  config/webpack.config.prod.js
  package.json
Labels: :eye: pending review

#1445 Move send component steps into one folder - Closes#1419
  .storybook/config.js
  jest.config.js
  src/components/converter/index.test.js
  src/components/newsFeed/index.test.js
  src/components/send/index.js
  src/components/send/steps/confirm/confirm.css
  src/components/send/steps/confirm/confirm.js
  src/components/send/steps/confirm/confirm.test.js
  src/components/send/steps/confirm/index.js
  src/components/send/steps/confirm/index.test.js
  src/components/send/steps/confirm/input.css
  src/components/send/steps/form/form.css
  src/components/send/steps/form/form.js
  src/components/send/steps/form/form.test.js
  src/components/send/steps/form/index.js
  src/components/send/steps/form/index.test.js
  src/components/send/steps/form/stories.js
Labels: :white_check_mark: ready

#1448 Make the app work on Windows - Closes #1440
  app/src/ledger.js
Labels: :white_check_mark: ready

#1458 Fix flaky tests - Closes #1455
  package.json
  src/utils/regex.js
  test/cypress/e2e/activity.spec.js
  test/cypress/e2e/bookmarks.spec.js
  test/cypress/e2e/delegates.spec.js
  test/cypress/e2e/help.spec.js
  test/cypress/e2e/settings.spec.js
  test/cypress/e2e/transfer.spec.js
  test/cypress/e2e/txDetails.spec.js
Labels: :white_check_mark: ready

#1423 Remember selected network - Closes #1337
  README.md
  src/actions/peers.js
  src/components/login/login.js
  src/constants/settings.js
  src/store/middlewares/account.js
  src/store/middlewares/account.test.js
  src/store/middlewares/peers.js
  src/store/middlewares/peers.test.js
  src/utils/login.js
  test/cypress/e2e/txDetails.spec.js
  test/cypress/support/commands.js
Labels: :white_check_mark: ready

#1473 Boolean in place of function onClick and userAgent console errors - Closes #1263
  src/components/login/login.css
  src/components/login/login.js
Labels: :white_check_mark: ready

#1474 Fix unstable passphrase test - Closes #1402
  src/components/passphraseCreation/index.test.js
Labels: :eye: pending review

#1475 Enable component test in Jest L36 to L65 - Closes #1433 #1434 #1435
  config/setupJest.js
  jest.config.js
  package.json
  src/components/toaster/toaster.test.js
Labels: :white_check_mark: ready

#1476 Enable component tests in Jest - Closes #1437 #1441 #1431 #1436 #1432 #1430
  config/setupJest.js
  jest.config.js
  src/components/passphraseInput/index.test.js
  src/components/quickTips/index.test.js
  src/components/sidechains/index.test.js
  src/components/votingListView/delegateRow.test.js
Labels: :white_check_mark: ready

#1469 Fix duplicated initialisation transaction - Closes #1343
  src/components/dashboard/index.js
  src/components/transactions/walletTransactions/index.js
  src/utils/transactions.js
  test/integration/dashboard.test.js
  test/integration/wallet.test.js
Labels: :building_construction: in progress

#1481 Remove old assets from previous builds - Closes #1480
  Jenkinsfile
Labels: :white_check_mark: ready

#1396 Validate and set custom node when creating new account - Closes #1326
  src/components/account/account.css
  src/components/login/index.js
  src/components/login/login.js
  src/components/login/login.test.js
  src/components/login/signUp.css
  src/components/login/signUp.js
Labels: :white_check_mark: ready

#1451 Fix API delegate - Closes #1359
  src/actions/transactions.js
  src/actions/voting.js
  src/actions/voting.test.js
  src/store/middlewares/voting.js
  src/store/middlewares/voting.test.js
  src/utils/delegates.js
  src/utils/delegates.test.js
Labels: :white_check_mark: ready

#1483 Remove duplicated 'npm run --silent test' line #Closes #1482
  Jenkinsfile
Labels: :white_check_mark: ready

#1485 Fix network used in registration - Closes #1484
  src/components/login/signUp.css
  src/components/login/signUp.js
  src/components/register/index.js
  src/components/register/register.js
  src/components/register/register.test.js
Labels: :white_check_mark: ready

#1491 Fix CSS warnings
  src/components/referenceInput/index.css
Labels: :white_check_mark: ready

#1498 Enable component tests in jest - Closes #1429
  app/src/menu.js
  app/src/menu.test.js
  app/src/modules/process.js
  app/src/modules/win.js
  app/src/modules/win.test.js
  jest.config.js
  karma.conf.js
  src/components/dashboard/currencyGraph.test.js
  src/components/header/header.test.js
  src/components/help/help.test.js
  src/components/newsFeed/index.test.js
  src/components/passphraseCreation/index.test.js
  src/utils/ipcLocale.test.js
  src/utils/notification.js
  src/utils/notification.test.js
  test/integration/wallet.test.js
Labels: :white_check_mark: ready

#1504 Fix typo "regiser delegate" - Closes #840
  src/components/registerDelegate/registerDelegate.test.js
  src/components/signMessage/signMessage.test.js
Labels: :white_check_mark: ready

#1503 Use LiskAmount to show vote weight - Closes #1477
  src/components/transactions/delegateStatistics.js
Labels: :white_check_mark: ready

#1444 Refactor TransactionsDetailView component - Closes #1282
  src/components/transactions/transactionDetailView/index.js
  src/components/transactions/transactionDetailView/transactionDetailDateField.js
  src/components/transactions/transactionDetailView/transactionDetailDateField.test.js
  src/components/transactions/transactionDetailView/transactionDetailView.css
  src/components/transactions/transactionDetailView/transactionDetailView.js
  src/components/transactions/transactionDetailView/transactionDetailView.test.js
  src/components/transactions/transactionDetailView/transactionDetailViewField.js
  src/components/transactions/transactionDetailView/transactionDetailViewRow.js
Labels: :building_construction: in progress

#1486 Change eslint rules - Closes #1383
  .eslintrc
  app/src/ledger.js
  app/src/modules/autoUpdater.js
  app/src/modules/win.js
  package-lock.json
  package.json
  src/actions/peers.js
  src/actions/transactions.js
  src/components/accountVisual/demo.js
  src/components/accountVisual/gradients.js
  src/components/accountVisual/index.js
  src/components/autoSuggest/index.js
  src/components/bookmark/bookmark.js
  src/components/converter/converter.js
  src/components/ledger/ledgerLogin.js
  src/components/login/login.js
  src/components/onboarding/index.js
  src/components/passphraseCreation/index.js
  src/components/passphraseInput/index.js
  src/components/passphraseSteps/index.js
  src/components/registerDelegate/steps/choose/choose.js
  src/components/send/steps/form/form.js
  src/components/transactions/transactionType.js
  src/components/transactions/transactionsList.js
  src/components/transactions/transactionsOverview.js
  src/components/votesPreview/index.js
  src/components/votingListView/delegateRow.test.js
  src/i18n-scanner.js
  src/store/middlewares/account.js
  src/store/middlewares/login.js
  src/store/reducers/search.js
  src/store/reducers/voting.js
  src/store/reducers/voting.test.js
  src/utils/api/delegate.test.js
  src/utils/api/ledger.js
  src/utils/ipcLocale.js
  src/utils/ledger.js
  src/utils/passphrase.js
  src/utils/similarWord.js
Labels: :white_check_mark: ready

#1411 Add feedback link to the sidebar - Closes #1410
  src/components/mainMenu/index.js
  src/components/mainMenu/index.test.js
  src/components/mainMenu/mainMenu.css
  src/components/mainMenu/mainMenu.js
  src/components/mainMenu/mainMenu.test.js
  src/constants/feedbackLinks.js
Labels: :white_check_mark: ready

#1502 Update/fix send/steps component with the changes made in Hub 1.6.0 - Closes #1501
  i18n/locales/en/common.json
  src/components/converter/converter.css
  src/components/converter/converter.js
  src/components/converter/converter.test.js
  src/components/send/steps/form/form.css
  src/components/send/steps/form/form.js
  src/components/send/steps/form/form.test.js
Labels: :white_check_mark: ready

#1507 Setup coverage checks for jest tests - Closes #1464
  jest.config.js
  src/components/newsFeed/newsFeed.test.js
  src/components/searchBar/index.test.js
Labels: :eye: pending review

#1490 Limit number of Jenkins builds retained - Closes #1488
  Jenkinsfile
Labels: :white_check_mark: ready

#1510 Change the snapshoted database owner to lisk - Closes #1509
  Jenkinsfile
  docs/TEST_GUIDE.md
  test/blockchain.db.gz
  test/cypress/e2e/delegates.spec.js
  test/dev_blockchain.db.gz
  test/e2e-test-setup.sh
Labels: :white_check_mark: ready

#1418 Second passphrase registration: Ugly timestamp error - Closes #1278
  i18n/locales/en/common.json
  package.json
  src/actions/account.js
  src/actions/account.test.js
  src/actions/secondPassphrase.js
  src/actions/secondPassphrase.test.js
  src/actions/transactions.js
  src/components/passphrase/ConfirmSecond/confirmSecond.css
  src/components/passphrase/ConfirmSecond/confirmSecond.js
  src/components/passphrase/ConfirmSecond/confirmSecond.test.js
  src/components/passphrase/ConfirmSecond/index.js
  src/components/passphrase/ConfirmSecond/index.test.js
  src/constants/actions.js
  src/store/middlewares/account.js
  src/store/reducers/index.js
  src/store/reducers/secondPassphrase.js
  src/store/reducers/secondPassphrase.test.js
  src/store/reducers/voting.js
Labels: :white_check_mark: ready

#1514 Implement bright and monochrome background - Closes #1494
  i18n/locales/en/common.json
  src/assets/css/styles.head.css
  src/components/account/account.css
  src/components/accountTransactions/accountTransactions.css
  src/components/app/variables.css
  src/components/autoSuggest/autoSuggest.css
  src/components/dashboard/dashboard.css
  src/components/dashboard/index.js
  src/components/header/customCountDown.css
  src/components/header/header.css
  src/components/header/header.js
  src/components/mainMenu/mainMenu.css
  src/components/toolbox/buttons/button.test.js
  src/index.html
Labels: :white_check_mark: ready

#1511 Refactor hardware wallet login - Closes #1438
  README.md
  i18n/locales/en/common.json
  jest.config.js
  package-lock.json
  package.json
  src/components/hwWallet/accountCard.css
  src/components/hwWallet/accountCard.js
  src/components/hwWallet/addAccountCard.js
  src/components/hwWallet/index.js
  src/components/hwWallet/ledgerLogin.css
  src/components/hwWallet/ledgerLogin.js
  src/components/hwWallet/unlockWallet.css
  src/components/hwWallet/unlockWallet.js
  src/components/ledger/index.js
  src/components/login/login.js
  src/constants/hwConstants.js
  src/constants/routes.js
  src/store/middlewares/login.js
  src/utils/api/ledger.js
  src/utils/ledger.js
  src/utils/to.js
  test/cypress/cypress.json
Labels: :white_check_mark: ready

#1446 Add sending ledger transaction - Closes #1317
  i18n/locales/en/common.json
  jest.config.js
  src/actions/peers.js
  src/actions/transactions.js
  src/actions/transactions.test.js
  src/components/hwWallet/accountCard.js
  src/components/hwWallet/ledgerLogin.js
  src/components/passphraseSteps/index.js
  src/components/resultBox/index.js
  src/components/resultBox/resultBox.js
  src/components/resultBox/resultBox.test.js
  src/components/send/steps/confirm/confirm.js
  src/components/transactions/transactionDetailView/transactionDetailView.js
  src/constants/actions.js
  src/store/reducers/transactions.js
  src/utils/ledger.js
  test/integration/login.test.js
  test/integration/wallet.test.js
  test/utils/genericStepDefinition.js
Labels: :white_check_mark: ready

#1517 Fix custom node login bug - Closes #1513
  src/components/login/login.js
Labels: :white_check_mark: ready

#1527 Update package.json to support node v6.15.0 - Closes #1
  .nvmrc
  package.json
Labels: :eye: pending review

#1524 Ping lisk core if it is available - Closes #881
  test/cypress/support/commands.js
Labels: :white_check_mark: ready
