Repository LiskHQ/lisk-desktop, pull requests merged in 2018-09, with the labels that each got.

#1230 Create guideline template and table of contents - Closes #1229
  .github/guideline_template.md
  CODE_OF_CONDUCT.md
  docs/CONTRIBUTING_GUIDE.md
  docs/DEVELOPMENT_GUIDE.md
  docs/PR-GUIDE.md
  docs/assets/PR-workflow.png
Labels: :white_check_mark: ready

#1228 autologout and delegates shouldnt be disabled when logged out - Closes #1208
  src/components/setting/setting.js
Labels: :white_check_mark: ready

#1226 Create new github templates - Closes 1190
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_proposal.md
  .github/issue_template.md
  .github/pull_request_template.md
Labels: :eye: pending review

#1173 Create general modal feedback form - closes #1166
  i18n/locales/en/common.json
  karma.conf.js
  src/actions/dialog.js
  src/assets/fonts/iconfont/icons.eot
  src/assets/fonts/iconfont/icons.html
  src/assets/fonts/iconfont/icons.ttf
  src/assets/fonts/iconfont/icons.woff
  src/components/feedbackForm/feedbackForm.css
  src/components/feedbackForm/feedbackForm.js
  src/components/feedbackForm/index.js
  src/components/feedbackForm/questionare.css
  src/components/feedbackForm/questionare.js
  src/components/feedbackForm/radioSelector.js
  src/components/fontIcon/fontIcon.css
  src/components/mainMenu/index.js
  src/components/mainMenu/mainMenu.js
  src/components/mainMenu/mainMenu.test.js
  src/constants/actions.js
  src/utils/app.js
Labels: :white_check_mark: ready

#1143 Strategy to migrate mocha to jest - Closes #1134
  .babelrc
  Jenkinsfile
  __mocks__/fileMock.js
  __mocks__/react-i18next.js
  config/setupJest.js
  docs/TEST_GUIDE.md
  jest.config.js
  package.json
  src/actions/search.js
  src/actions/search.test.js
  src/actions/transactions.js
  src/components/login/index.js
  src/components/passphrase/ConfirmSecond/confirmSecond.js
  src/components/passphrase/confirm/index.test.js
  src/components/transactions/amount.test.js
  src/components/transactions/transactionDetailView.test.js
  src/components/transactions/transactionDetailViewRow.js
  src/components/transactions/transactionOverview.js
  src/utils/api/peers.js
  src/utils/loading.js
  test/integration/transactionID.test.js
Labels: :eye: pending review

#1244 Fix searchbar placeholder overflow - Closes #1241
  src/components/autoSuggest/autoSuggest.css
Labels: :white_check_mark: ready

#1240 Electron update dialog showing some errors - Closes #1225
  app/src/modules/updateModal.js
  i18n/locales/en/common.json
Labels: :white_check_mark: ready

#1243 Set active peer on app start - Closes #1242
  src/store/index.js
  src/store/middlewares/login.js
  src/store/middlewares/peers.js
  src/utils/account.test.js
Labels: :white_check_mark: ready

#1248 Remove crucial parts of saved accounts - Closes #1247
  src/components/app/index.js
  src/store/middlewares/index.js
  src/store/reducers/index.js
Labels: :white_check_mark: ready

#1250 Fix converted fee value - #1249
  src/components/converter/converter.js
Labels: :white_check_mark: ready

#1246 Prevent setProgressBar error in autoUpdater - Closes #1207
  app/src/modules/autoUpdater.js
  app/src/modules/autoUpdater.test.js
  jest.config.js
Labels: :ballot_box_with_check: pending QA, :white_check_mark: ready

#1245 Design updates for smaller screen sizes. - Closes #944
  src/components/passphrase/confirm/confirm.css
  src/components/passphrase/confirm/index.js
  src/components/passphrase/create/create.css
  src/components/passphrase/create/create.js
  src/components/passphrase/create/shapes.js
  src/components/passphraseCreation/index.js
  src/components/passphraseCreation/passphraseCreation.css
  src/components/request/request.css
  src/components/sendReadable/send.js
  src/components/sendReadable/sendReadable.css
Labels: :white_check_mark: ready

#1223 Add specs for feature feedback - Closes #1161
  docs/1161_SPECS.md
  src/store/middlewares/savedSettings.js
  src/store/middlewares/socket.js
Labels: :white_check_mark: ready

#1184 Stop passing peers to delegate actions - Closes #1148
  src/actions/account.test.js
  src/actions/delegate.js
  src/actions/delegate.test.js
  src/actions/transactions.test.js
  src/actions/voting.test.js
  src/components/accountTransactions/index.js
  src/components/authenticate/authenticate.js
  src/components/authenticate/authenticate.test.js
  src/components/confirmVotes/confirmVotes.test.js
  src/components/confirmVotes/index.js
  src/components/confirmVotes/index.test.js
  src/components/registerDelegate/registerDelegate.js
  src/components/searchBar/index.js
  src/components/secondPassphrase/secondPassphrase.test.js
  src/components/sendReadable/send.test.js
  src/components/sendWritable/index.js
  src/components/sendWritable/send.test.js
  src/components/transactions/explorerTransactions/index.js
  src/components/voteUrlProcessor/index.js
  src/components/votingListView/votingListView.test.js
  src/constants/actions.js
  src/store/reducers/delegate.js
  src/store/reducers/delegate.test.js
Labels: :white_check_mark: ready

#1270 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/config.yml
  docs/CONTRIBUTING_GUIDE.md
Labels: :eye: pending review

#1260 Create initial e2e test setup using cypress - Closes #1197
  .gitignore
  Jenkinsfile
  package.json
  protractor.conf.js
  src/components/header/header.js
  test/cypress/.eslintrc
  test/cypress/cypress.json
  test/cypress/e2e/ex-protractor-cucumber/explorer.spec.js
  test/cypress/e2e/ex-protractor-cucumber/followedAccount.spec.js
  test/cypress/e2e/ex-protractor-cucumber/login.spec.js
  test/cypress/e2e/ex-protractor-cucumber/onboarding.spec.js
  test/cypress/e2e/ex-protractor-cucumber/registerDelegate.spec.js
  test/cypress/e2e/ex-protractor-cucumber/registerSecondPassphrase.spec.js
  test/cypress/e2e/ex-protractor-cucumber/send.spec.js
  test/cypress/e2e/ex-protractor-cucumber/signMessage.spec.js
  test/cypress/e2e/ex-protractor-cucumber/voting.spec.js
  test/cypress/e2e/header.spec.js
  test/cypress/e2e/login.spec.js
  test/cypress/fixtures/example.json
  test/cypress/plugins/index.js
  test/cypress/support/commands.js
  test/cypress/support/index.js
  test/e2e/.eslintrc.json
  test/e2e/explorer.feature
  test/e2e/followedAccounts.feature
  test/e2e/login.feature
  test/e2e/onboarding.feature
  test/e2e/registerDelegate.feature
  test/e2e/registerSecondPassphrase.feature
  test/e2e/send.feature
  test/e2e/signMessage.feature
  test/e2e/step_definitions/explorer.step.js
  test/e2e/step_definitions/generic.step.js
  test/e2e/step_definitions/hooks.js
  test/e2e/step_definitions/login.step.js
  test/e2e/step_definitions/secondPassphrase.step.js
  test/e2e/step_definitions/send.step.js
  test/e2e/step_definitions/top.step.js
  test/e2e/step_definitions/transactions.step.js
  test/e2e/step_definitions/voting.step.js
  test/e2e/support/localStorage.js
  test/e2e/support/util.js
  test/e2e/voting.feature
Labels: :white_check_mark: ready

#1265 Remove text from onboarding step - Closes #1259
  i18n/locales/en/common.json
  src/components/onboarding/steps.js
Labels: :white_check_mark: ready

#1276 Add encoding to urls on requesting LSK - Closes #1189
  src/components/request/confirmRequest.js
  src/components/request/index.js
Labels: :white_check_mark: ready

#1272 Fix network showing for mainnet - Closes #1251
  jest.config.js
  src/components/account/account.js
  src/components/account/account.test.js
Labels: :white_check_mark: ready

#1273 Fix pending details missing - Closes #1269
  src/components/transactions/explorerTransactions/index.test.js
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionDetailView.test.js
  test/integration/transactionID.test.js
Labels: :white_check_mark: ready

#1267 Remove saved accounts code - Closes #1141
  i18n/locales/de/common.json
  i18n/locales/en/common.json
  jest.config.js
  karma.conf.js
  src/actions/peers.test.js
  src/actions/savedAccounts.js
  src/actions/savedAccounts.test.js
  src/components/dialog/dialog.test.js
  src/components/header/header.test.js
  src/components/header/index.js
  src/components/header/index.test.js
  src/components/login/index.js
  src/components/login/index.test.js
  src/components/login/login.js
  src/components/savedAccounts/accountCard.js
  src/components/savedAccounts/accountCard.test.js
  src/components/savedAccounts/addAccountCard.js
  src/components/savedAccounts/card.css
  src/components/savedAccounts/index.js
  src/components/savedAccounts/index.test.js
  src/components/savedAccounts/savedAccounts.css
  src/components/savedAccounts/savedAccounts.js
  src/components/savedAccounts/savedAccounts.test.js
  src/constants/actions.js
  src/store/index.js
  src/store/middlewares/savedAccounts.js
  src/store/middlewares/savedAccounts.test.js
  src/store/reducers/savedAccounts.js
  src/store/reducers/savedAccounts.test.js
  src/store/subscribers/savedAccounts.js
  src/store/subscribers/savedAccounts.test.js
  src/utils/applyDeviceClass.js
  src/utils/savedAccounts.js
  test/integration/dashboard.test.js
  test/integration/login.test.js
  test/integration/wallet.test.js
Labels: :white_check_mark: ready

#1255 Create guideline for Epic creation workflow
  docs/DEVELOPMENT_GUIDE.md
  docs/EPIC_SPECIFICATION_GUIDE.md
  docs/assets/Epic-workflow.png
Labels: :white_check_mark: ready

#1258 Upgrade vulnerable dependencies with no breaking changes - Closes #1210
  .gitignore
  package-lock.json
  package.json
Labels: :white_check_mark: ready

#1287 Fix rendering error on tx details - Closes #1284
  src/components/transactions/transactionDetailView.js
Labels: :white_check_mark: ready

#1288 Fix Lisk Academy logo colors
  src/assets/images/dashboard/academy.svg
Labels: :eye: pending review

#1291 Remove saved settings middleware - Closes #1290
  src/store/index.js
  src/store/middlewares/index.js
  src/store/middlewares/savedSettings.js
  src/store/middlewares/savedSettings.test.js
  src/store/subscribers/settings.js
  src/store/subscribers/settings.test.js
  src/utils/settings.js
  src/utils/settings.test.js
Labels: :eye: pending review

#1199 Improve login page testing dev experience - Closes #1187
  README.md
  jest.config.js
  src/constants/settings.js
  src/store/middlewares/account.js
  src/store/middlewares/account.test.js
  src/utils/login.js
  test/integration/dashboard.test.js
  test/integration/login.test.js
  test/integration/registerDelegate.test.js
Labels: :white_check_mark: ready

#1268 Align size of gray parts - Closes #1201
  src/components/help/help.css
  src/components/help/help.js
  src/components/menuBar/menuBar.css
  src/components/setting/setting.css
  src/components/setting/setting.js
  src/components/votesPreview/votesPreview.css
  src/components/voting/voting.css
Labels: :building_construction: in progress

#1306 E2E tests for settings - Closes #1304
  src/components/setting/setting.js
  test/constants/networks.js
  test/cypress/e2e/settings.spec.js
  test/cypress/support/commands.js
Labels: :eye: pending review

#1309 E2E tests for help - Closes #1308
  test/cypress/e2e/ex-protractor-cucumber/onboarding.spec.js
  test/cypress/e2e/help.spec.js
  test/cypress/e2e/settings.spec.js
  test/cypress/support/commands.js
Labels: :eye: pending review

#1310 E2E tests for login - Closes #1307
  test/constants/accounts.js
  test/cypress/e2e/ex-protractor-cucumber/login.spec.js
  test/cypress/e2e/header.spec.js
  test/cypress/e2e/login.spec.js
  test/cypress/support/commands.js
Labels: :white_check_mark: ready
