Repository LiskHQ/lisk-desktop, pull requests merged in 2018-04, with the labels that each got.

#621 Change wordings of back to lisk.io link - Closes #599
  i18n/locales/en/common.json
  src/components/login/login.css
  src/components/login/login.js
Labels: :building_construction: in progress

#655 Split passphrase/create css into smaller files - subTask #513
  src/components/passphrase/create/create.css
  src/components/passphrase/create/index.js
  src/components/passphrase/create/shapes.css
  src/components/passphrase/create/shapes.js
  src/components/register/register.css
Labels: :eye: pending review

#640 Split transactions.css into smaller files - subTask #513
  src/components/transactions/states.css
  src/components/transactions/transactionDetailView.css
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionList.css
  src/components/transactions/transactionList.js
  src/components/transactions/transactionRow.css
  src/components/transactions/transactionRow.js
  src/components/transactions/transactions.css
  src/components/transactions/transactionsHeader.js
Labels: :eye: pending review

#648 Remove and add electron menu items - Closes #646
  app/src/menu.js
  i18n/locales/en/common.json
Labels: :eye: pending review

#667 Test against core 0.9.12a from lisk-docker - Closes #665
  Jenkinsfile
Labels: :eye: pending review

#666 Second passphrase doesn't inform about balance - Closes #637
  i18n/locales/en/common.json
  src/components/passphrase/create/create.css
  src/components/passphrase/create/index.js
  src/components/passphrase/createSecond/index.js
  src/components/passphrase/safekeeping/index.js
  src/components/secondPassphrase/secondPassphrase.js
  test/e2e/registerSecondPassphrase.feature
Labels: :eye: pending review

#673 Show loader until peer is set (second attempt) - Closes #510
  src/components/accountTransactions/index.test.js
  src/components/app/index.js
  src/components/app/index.test.js
  src/components/loadingBar/index.js
  src/components/loadingBar/index.test.js
  src/components/loadingBar/loadingBar.js
  src/components/loadingBar/loadingBar.test.js
  src/components/transactions/transactionList.js
Labels: :eye: pending review

#617 Update configs for babel-preset-env - Closes #539
  config/webpack.config.js
  package.json
Labels: :eye: pending review

#653 Remove noop in seed initialization - Subtask #663
  src/utils/passphrase.js
Labels: :white_check_mark: ready

#675 Fix regression in delegate list - Closes #635
  src/components/confirmVotes/confirmVotes.css
  src/components/votesPreview/votesPreview.css
  src/components/voting/voting.css
Labels: :eye: pending review

#682 Fix Account visual location in xSmall
  src/components/header/header.css
Labels: :eye: pending review

#677 Fix vote protocol twice in row - Closes #661
  src/components/mainMenu/mainMenu.js
  src/components/mainMenu/mainMenu.test.js
  src/utils/externalLinks.js
  src/utils/externalLinks.test.js
Labels: :eye: pending review

#645 Saved Accounts improvements on xs breakpoint - Closes #590
  src/components/savedAccounts/card.css
  src/components/savedAccounts/savedAccounts.css
Labels: :eye: pending review

#690 Delegates features menu breaks layout in tablet portrait - Closes #689
  src/components/setting/setting.css
Labels: :eye: pending review

#692 Send to address button doesnt show send form - Closes #670
  src/components/accountInitialization/index.js
  src/components/send/index.js
Labels: :white_check_mark: ready

#688 Remove extra margin in account detail page - Closes #687
  src/components/accountTransactions/accountTransactions.css
  src/components/accountTransactions/index.js
Labels: :eye: pending review

#696 Fix second passphrase back button - Closes #695
  src/components/secondPassphrase/secondPassphrase.js
Labels: :eye: pending review

#697 Double click on "Yes it's safe" breaks whole app - Closes #642
  src/components/passphrase/safekeeping/index.js
Labels: :white_check_mark: ready

#698 Saved account style improvements in xs - Closes #590
  src/components/savedAccounts/card.css
  src/components/savedAccounts/savedAccounts.css
Labels: :eye: pending review

#676 Update balance in account switcher - Closes #595
  src/components/savedAccounts/savedAccounts.js
  src/store/middlewares/savedAccounts.js
  src/store/middlewares/savedAccounts.test.js
Labels: :white_check_mark: ready

#705 Enable delegates after opening - Closes #701
  src/components/voteUrlProcessor/index.js
  src/components/voteUrlProcessor/voteUrlProcessor.js
  src/components/voteUrlProcessor/voteUrlProcessor.test.js
Labels: :white_check_mark: ready

#625 Improve url scheme - Closes #608
  src/components/app/index.js
  src/components/app/index.test.js
  src/components/customRoute/index.js
  src/components/customRoute/index.test.js
  src/components/dashboard/index.js
  src/components/dashboard/index.test.js
  src/components/dialog/dialog.test.js
  src/components/login/login.js
  src/components/login/login.test.js
  src/components/mainMenu/mainMenu.js
  src/components/mainMenu/mainMenu.test.js
  src/components/onboarding/index.js
  src/components/onboarding/steps.js
  src/components/passphrase/ConfirmSecond/confirmSecond.js
  src/components/privateRoute/index.js
  src/components/register/register.js
  src/components/savedAccounts/addAccountCard.js
  src/components/savedAccounts/savedAccounts.js
  src/components/savedAccounts/savedAccounts.test.js
  src/components/search/keyAction.js
  src/components/search/keyAction.test.js
  src/components/secondPassphrase/secondPassphrase.js
  src/components/sendTo/index.js
  src/components/sendTo/sendTo.test.js
  src/components/setting/setting.css
  src/components/setting/setting.js
  src/components/setting/setting.test.js
  src/components/transactions/transactionDetailView.js
  src/constants/routes.js
  src/utils/externalLinks.js
  test/e2e/explorer.feature
  test/e2e/registerDelegate.feature
  test/e2e/registerSecondPassphrase.feature
  test/e2e/savedAccounts.feature
  test/e2e/transactions.feature
  test/e2e/voting.feature
  test/integration/accountSwitch.test.js
Labels: :building_construction: in progress

#639 Add delegate name to account page - Closes #600
  i18n/locales/en/common.json
  src/components/accountTransactions/index.js
  src/components/sendTo/index.js
  src/components/sendTo/sendTo.css
  src/components/sendTo/sendTo.test.js
  src/store/middlewares/transactions.js
  src/store/middlewares/transactions.test.js
  src/store/reducers/account.js
  src/store/reducers/transactions.js
  test/integration/accountTransactions.test.js
  test/integration/wallet.test.js
Labels: :white_check_mark: ready

#679 Prevent autoupdater error when there's tag without published release - Closes #647
  app/src/modules/autoUpdater.js
  app/src/modules/autoUpdater.test.js
Labels: :eye: pending review

#707 Add meta tags - Closes #702
  src/assets/images/og-logo.png
  src/index.html
Labels: :building_construction: in progress

#699 Improve documentation for community contributors - Closes #660
  CONTRIBUTING.md
  README.md
  docs/assets/issue.png
  docs/assets/pr.png
Labels: :eye: pending review

#710 Write tests for onboarding - Closes #632
  karma.conf.js
  src/components/app/index.js
  src/components/onboarding/index.js
  src/components/onboarding/onboarding.test.js
Labels: :white_check_mark: ready

#712 Refactor and Increase the unit tests of SliderCheckbox component - Closes #242
  karma.conf.js
  src/components/toolbox/sliderCheckbox/index.js
  src/components/toolbox/sliderCheckbox/index.test.js
Labels: :eye: pending review

#708 Add release notes to desktop update popup - Closes #694
  app/src/main.js
  app/src/modules/autoUpdater.js
  app/src/modules/autoUpdater.test.js
  app/src/modules/updateModal.js
  app/src/modules/updateModal.test.js
  app/src/styles.dialog.css
  app/src/update.html
  config/webpack.config.electron.js
  i18n/locales/en/common.json
  package.json
Labels: :eye: pending review

#680 Review and reduce amount of e2e tests - #149
  src/components/delegateList/votingHeader.js
  test/e2e/login.feature
  test/e2e/registerSecondPassphrase.feature
  test/e2e/send.feature
  test/e2e/transactions.feature
  test/e2e/voting.feature
Labels: :building_construction: in progress

#709 Increase test coverage - Closes #534
  karma.conf.js
  src/components/accountVisual/index.test.js
  src/components/authenticate/authenticate.test.js
  src/components/authenticate/index.test.js
  src/components/multiStep/index.js
  src/components/passphrase/create/index.test.js
  src/components/passphrase/createSecond/index.js
  src/components/passphrase/createSecond/index.test.js
  src/components/passphrase/safekeeping/index.js
  src/components/passphrase/safekeeping/index.test.js
  src/components/registerDelegate/index.test.js
  src/components/resultBox/resultBox.js
  src/components/secondPassphrase/index.js
  src/components/secondPassphrase/secondPassphrase.js
  src/components/secondPassphrase/secondPassphrase.test.js
  src/components/toolbox/transitionWrapper/index.js
  src/components/toolbox/transitionWrapper/index.test.js
  test/integration/register.test.js
  test/integration/voting.test.js
Labels: :eye: pending review

#664 Implement delegate registration - Closes #65
  i18n/locales/en/common.json
  karma.conf.js
  src/actions/account.js
  src/actions/account.test.js
  src/actions/delegate.js
  src/components/app/index.js
  src/components/app/variables.css
  src/components/delegateList/delegateList.js
  src/components/delegateList/index.js
  src/components/delegateList/votingHeader.css
  src/components/delegateList/votingHeader.js
  src/components/multiStep/multiStep.css
  src/components/passphraseSteps/index.js
  src/components/registerDelegate/index.js
  src/components/registerDelegate/index.test.js
  src/components/registerDelegate/registerDelegate.css
  src/components/registerDelegate/registerDelegate.js
  src/components/registerDelegate/registerDelegate.test.js
  src/components/registerDelegate/steps/choose/choose.css
  src/components/registerDelegate/steps/choose/choose.js
  src/components/registerDelegate/steps/choose/index.js
  src/components/registerDelegate/steps/confirm/confirm.css
  src/components/registerDelegate/steps/confirm/confirm.js
  src/components/registerDelegate/steps/confirm/index.js
  src/components/registerDelegate/steps/passphraseSteps.css
  src/components/registerDelegate/steps/steps.css
  src/components/transactions/index.test.js
  src/components/voting/index.test.js
  src/constants/actions.js
  src/constants/routes.js
  src/store/middlewares/account.test.js
  src/store/reducers/delegate.js
  src/store/reducers/index.js
Labels: :building_construction: in progress

#716 Fix the focused input cursor issue in iOS - Closes #691
  src/components/app/app.css
  src/components/delegateList/votingHeader.css
  src/components/toolbox/sliderCheckbox/index.js
Labels: :eye: pending review

#711 Add 404 page for all pages - Closes #584
  src/components/app/index.js
  src/components/customRoute/index.js
  src/components/search/keyAction.js
  src/components/search/keyAction.test.js
  src/constants/routes.js
  src/utils/app.js
  src/utils/app.test.js
Labels: :eye: pending review

#727 Add @pending to account init e2e test
  test/e2e/send.feature
Labels: :eye: pending review

#718 Write docs for protocols - Closes #685
  docs/PROTOCOL_GUIDE.md
  docs/assets/lisk_wallet.png
  docs/assets/voting_protocol.png
Labels: :eye: pending review

#734 Change "Register as a delegate" to "Be a delegate" - Closes #722
  i18n/locales/en/common.json
  src/components/delegateList/votingHeader.js
Labels: :eye: pending review

#732 Add integration tests for dashboard - Closes #719
  src/components/dashboard/index.test.js
  test/integration/dashboard.test.js
Labels: :white_check_mark: ready

#706 Animate shape colors in registration - Closes #703
  config/webpack.config.react.js
  src/assets/images/register-shapes/circle-left.svg
  src/assets/images/register-shapes/circle.svg
  src/assets/images/register-shapes/circle1.svg
  src/assets/images/register-shapes/small-circle.svg
  src/assets/images/register-shapes/small-triangle.svg
  src/assets/images/register-shapes/square-left.svg
  src/assets/images/register-shapes/square-right.svg
  src/assets/images/register-shapes/triangle-left.svg
  src/assets/images/register-shapes/triangle.svg
  src/assets/images/register-shapes/very-small-circle.svg
  src/components/passphrase/create/colorSchemes.js
  src/components/passphrase/create/index.js
  src/components/passphrase/create/movableShape.js
  src/components/passphrase/create/movableShape.test.js
  src/components/passphrase/create/shapes.css
  src/components/passphrase/create/shapes.js
Labels: :white_check_mark: ready

#582 Create a guide for writing tests - Closes #516
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/TEST_GUIDE.md
Labels: :eye: pending review

#733 Make Launch protocol `lisk://add-account?showNetwork=true` work
  src/components/login/login.js
Labels: :eye: pending review

#741 Fix an issue in marking missing words - Closes #717
  src/components/passphrase/confirm/form.css
Labels: :eye: pending review

#758 A tiny hack to fix the issue with border radius in Safari - Closes #749
  src/components/passphrase/createSecond/progressBar.css
Labels: :eye: pending review

#740 Refactor Price chart API call to redux action - Closes #293
  src/actions/liskService.js
  src/components/dashboard/currencyGraph.js
  src/components/dashboard/currencyGraph.test.js
  src/constants/actions.js
  src/store/reducers/index.js
  src/store/reducers/liskService.js
  src/utils/api/liskService.js
  test/integration/dashboard.test.js
Labels: :eye: pending review

#736 Remove malformed html in index.html - Closes #581
  src/index.html
Labels: :eye: pending review

#748 Display amount converted - Closes #662
  karma.conf.js
  src/components/converter/converter.css
  src/components/converter/index.js
  src/components/converter/index.test.js
  src/components/sendWritable/send.js
  src/utils/api/liskService.js
Labels: :eye: pending review

#754 Fix too high CPU
  src/components/accountVisual/accountVisual.css
Labels: :white_check_mark: ready

#757 Implement welcome bot - Closes #715
  .github/config.yml
Labels: :eye: pending review

#726 Add vote transaction details - Closes #704
  i18n/locales/en/common.json
  src/actions/transactions.js
  src/components/accountTransactions/index.test.js
  src/components/accountVisual/demo.js
  src/components/authInputs/authInputs.js
  src/components/login/login.js
  src/components/passphrase/ConfirmSecond/confirmSecond.js
  src/components/passphrase/confirm/index.js
  src/components/passphrase/create/index.js
  src/components/passphraseSteps/index.js
  src/components/registerDelegate/steps/confirm/confirm.js
  src/components/savedAccounts/accountCard.js
  src/components/singleTransaction/index.js
  src/components/singleTransaction/singleTransaction.css
  src/components/transactions/amount.js
  src/components/transactions/index.js
  src/components/transactions/transactionDetailView.css
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionDetailView.test.js
  src/components/transactions/transactionType.js
  src/components/transactions/transactionType.test.js
  src/constants/actions.js
  src/store/middlewares/login.js
  src/store/middlewares/savedAccounts.js
  src/store/middlewares/transactions.js
  src/store/middlewares/transactions.test.js
  src/store/reducers/transaction.js
  src/store/reducers/transaction.test.js
  src/utils/account.js
  src/utils/account.test.js
  src/utils/api/account.js
  src/utils/api/account.test.js
  src/utils/savedAccounts.js
  test/integration/accountTransactions.test.js
  test/integration/transactionID.test.js
Labels: :eye: pending review

#763 Add vote launch protocol info box
  i18n/locales/en/common.json
  src/actions/voting.js
  src/components/delegateList/delegateList.js
  src/components/delegateList/delegateList.test.js
  src/components/delegateList/index.test.js
  src/components/delegateList/votingHeader.css
  src/components/delegateList/votingHeader.js
  src/components/delegateSidebar/index.js
  src/components/registerDelegate/steps/choose/choose.js
  src/components/voteUrlProcessor/index.js
  src/components/voteUrlProcessor/voteUrlProcessor.css
  src/components/voteUrlProcessor/voteUrlProcessor.js
  src/components/votesPreview/index.js
  src/components/votesPreview/votesPreview.css
  src/components/voting/index.test.js
  src/components/voting/voting.js
  src/components/voting/voting.test.js
  src/constants/actions.js
  test/integration/voting.test.js
Labels: :white_check_mark: ready

#762 Send emails on failures - Closes #761
  Jenkinsfile
Labels: :eye: pending review

#768 Fix a bug in showing vote summary - Closes #728
  src/components/registerDelegate/registerDelegate.test.js
  src/components/voting/index.test.js
  src/components/voting/voting.js
  src/components/votingListView/delegateList.js
  src/components/votingListView/delegateList.test.js
  src/components/votingListView/delegateRow.js
  src/components/votingListView/delegateRow.test.js
  src/components/votingListView/disableMenu.css
  src/components/votingListView/index.js
  src/components/votingListView/index.test.js
  src/components/votingListView/listLabels.js
  src/components/votingListView/voteCheckbox.css
  src/components/votingListView/voteCheckbox.js
  src/components/votingListView/voteCheckbox.test.js
  src/components/votingListView/voteList.js
  src/components/votingListView/voteRow.js
  src/components/votingListView/voteRow.test.js
  src/components/votingListView/votingHeader.css
  src/components/votingListView/votingHeader.js
  src/components/votingListView/votingHeader.test.js
  src/components/votingListView/votingListView.css
  src/components/votingListView/votingListView.js
  src/components/votingListView/votingListView.test.js
  src/store/middlewares/voting.js
  src/store/reducers/voting.js
  src/store/reducers/voting.test.js
Labels: :eye: pending review
