Repository LiskHQ/lisk-desktop, pull requests merged in 2018-03, with the labels that each got.

#490 Account switcher background scrolls away #470
  src/components/backgroundMaker/index.js
  src/components/savedAccounts/savedAccounts.css
  src/components/savedAccounts/savedAccounts.js
Labels: :eye: pending review

#489 Integration test for login page - Subtask #103
  test/integration/login.test.js
  test/utils/genericStepDefinition.js
Labels: :eye: pending review

#448 Fix @integration: Wallet test that sometimes fails - Closes #426
  app/src/modules/localeHandler.test.js
  test/integration/wallet.test.js
Labels: :eye: pending review

#503 Improve test coverage - Closes #471
  karma.conf.js
  src/components/confirmVotes/confirmVotes.js
  src/components/confirmVotes/confirmVotes.test.js
  src/components/passphrase/info/index.js
Labels: :eye: pending review

#497 Hide transaction list and empty message when loading - Closes #348
  src/components/accountTransactions/index.js
  src/components/accountTransactions/index.test.js
  src/components/dashboard/index.js
  src/components/dashboard/index.test.js
  src/components/sendTo/index.js
  src/components/transactions/index.test.js
  src/components/transactions/transactionList.js
  src/components/transactions/transactionOverview.js
  src/components/voting/index.test.js
  src/store/middlewares/transactions.js
  test/integration/accountTransactions.test.js
  test/integration/wallet.test.js
Labels: :eye: pending review

#506 Remove unused code for forging - Closes #505
  i18n/locales/en/common.json
  karma.conf.js
  src/actions/forging.js
  src/actions/forging.test.js
  src/components/app/index.js
  src/components/app/index.test.js
  src/components/forging/circularProgressbar.css
  src/components/forging/delegateStats.js
  src/components/forging/delegateStats.test.js
  src/components/forging/forgedBlocks.js
  src/components/forging/forgedBlocks.test.js
  src/components/forging/forging.css
  src/components/forging/forging.js
  src/components/forging/forging.test.js
  src/components/forging/forgingStats.js
  src/components/forging/forgingStats.test.js
  src/components/forging/forgingTitle.js
  src/components/forging/forgingTitle.test.js
  src/components/forging/index.js
  src/components/forging/index.test.js
  src/components/login/login.js
  src/components/login/login.test.js
  src/components/mainMenu/mainMenu.js
  src/constants/actions.js
  src/store/middlewares/account.js
  src/store/middlewares/account.test.js
  src/store/reducers/forging.js
  src/store/reducers/forging.test.js
  src/store/reducers/index.js
  src/utils/api/forging.js
  src/utils/api/forging.test.js
  src/utils/routes.js
  test/e2e/step_definitions/forging.step.js
Labels: :eye: pending review

#501 Increase unit test coverage of reducers - Closes #496
  karma.conf.js
  src/store/reducers/savedAccounts.test.js
  src/store/reducers/transactions.test.js
  src/store/reducers/voting.test.js
Labels: :eye: pending review

#518 Update the desktop app icon - Closes #495
  app/assets/lisk.icns
  app/assets/lisk.ico
  app/assets/lisk.png
  app/package.json
  build/icon.icns
  build/icon.ico
Labels: :eye: pending review

#520 Unify font size of ui - Closes #363
  src/components/app/variables.css
  src/components/box/box.css
  src/components/confirmVotes/confirmVotes.css
  src/components/dashboard/currencyGraph.css
  src/components/dialog/dialog.css
  src/components/emptyState/emptyState.css
  src/components/mainMenu/mainMenu.css
  src/components/menuBar/menuBar.css
  src/components/resultBox/resultBox.css
  src/components/sendReadable/sendReadable.css
  src/components/sendWritable/sendWritable.css
  src/components/setting/setting.css
  src/components/toolbox/inputs/input.css
  src/components/votesPreview/votesPreview.css
Labels: :eye: pending review

#528 Ensure all css files are named same as component - Closes #511
  src/components/copyToClipboard/copyToClipboard.css
  src/components/copyToClipboard/index.js
  src/components/dashboard/dashboard.css
  src/components/dashboard/index.js
  src/components/fontIcon/fontIcon.css
  src/components/fontIcon/index.js
  src/components/singleTransaction/index.js
  src/components/singleTransaction/singleTransaction.css
  src/components/transactionDashboard/index.js
  src/components/transactionDashboard/transactionDasboard.css
Labels: :eye: pending review

#537 Post Slack notifications to lisk-ci-hub channel
  Jenkinsfile
Labels: :eye: pending review

#524 Change typographical elements to use px - Closes #85
  config/webpack.config.react.js
  src/components/app/type.css
  src/components/app/variables.css
  src/components/confirmVotes/confirmVotes.css
  src/components/dashboard/currencyGraph.css
  src/components/dashboard/styles.css
  src/components/delegateList/delegateList.css
  src/components/dialog/dialog.css
  src/components/fontIcon/icons.css
  src/components/login/login.css
  src/components/multiStep/multiStep.css
  src/components/passphrase/confirm/confirm.css
  src/components/passphrase/create/create.css
  src/components/passphrase/safekeeping/safekeeping.css
  src/components/passphraseSteps/passphraseSteps.css
  src/components/resultBox/resultBox.css
  src/components/savedAccounts/savedAccounts.css
  src/components/sendReadable/sendReadable.css
  src/components/sendTo/sendTo.css
  src/components/sendWritable/sendWritable.css
  src/components/singleTransaction/transaction.css
  src/components/toolbox/buttons/css/iconButton.css
  src/components/toolbox/buttons/css/importantButton.css
  src/components/toolbox/buttons/css/lightButton.css
  src/components/toolbox/buttons/iconButton.js
  src/components/toolbox/tables/css/theme.css
  src/components/toolbox/tables/table.js
  src/components/toolbox/tables/table.test.js
  src/components/transactions/transactions.css
  src/components/votesPreview/votesPreview.css
Labels: :eye: pending review

#527 Fix Nan for very small amount in 'Activity tab' - Closes #507
  karma.conf.js
  package.json
  src/components/confirmVotes/confirmVotes.js
  src/components/confirmVotes/confirmVotes.test.js
  src/components/passphrase/info/index.js
Labels: :eye: pending review

#515 Improve middleware test coverage up to 100% - Closes #157
  karma.conf.js
  src/store/middlewares/account.test.js
  src/store/middlewares/login.test.js
  src/store/middlewares/peers.js
  src/store/middlewares/savedAccounts.js
  src/store/middlewares/savedAccounts.test.js
  src/store/middlewares/socket.js
  src/store/middlewares/socket.test.js
  test/integration/accountSwitch.test.js
Labels: :white_check_mark: ready

#543 Fix mixed transactions in explorer - Closes #508
  src/store/middlewares/account.js
  src/store/middlewares/account.test.js
Labels: :eye: pending review

#522 Generate Index.html with webpack - Closes #514
  config/webpack.config.prod.js
  config/webpack.config.react.js
  package.json
  src/assets/css/styles.head.css
  src/index.html
  src/main.js
Labels: :eye: pending review

#538 Move the default network setting outside of built bundles - Closes #491
  .eslintignore
  .eslintrc
  .gitignore
  Jenkinsfile
  config/webpack.config.react.js
  config/webpack.config.test.js
  package.json
  src/components/register/register.test.js
  src/constants/env.js
  src/constants/networks.js
  src/index.html
Labels: :eye: pending review

#546 Revert removal of istambul ignore - Closes #157
  src/store/middlewares/savedAccounts.js
Labels: :eye: pending review

#541 Improve checkbox component - Closes #183
  karma.conf.js
  src/components/confirmVotes/confirmVotes.js
  src/components/multiStep/multiStep.css
  src/components/passphrase/safekeeping/index.js
  src/components/setting/languageSwitcher.css
  src/components/setting/setting.js
  src/components/toolbox/sliderCheckbox/checkbox.css
  src/components/toolbox/sliderCheckbox/index.js
  src/components/toolbox/sliderCheckbox/index.test.js
Labels: :building_construction: in progress

#550 Fix the launch protocol for send - Closes #280
  src/components/dashboard/index.js
  src/components/dashboard/index.test.js
  src/components/resultBox/resultBox.js
  src/components/resultBox/resultBox.test.js
  src/components/send/index.js
  src/components/send/index.test.js
  src/components/sendWritable/send.js
  src/components/transactionDashboard/index.js
  test/integration/wallet.test.js
Labels: :eye: pending review

#542 Refactor route definition - Closes #499
  src/components/app/index.js
  src/components/app/index.test.js
  src/components/dashboard/index.js
  src/components/dialog/dialog.test.js
  src/components/header/header.js
  src/components/header/header.test.js
  src/components/login/login.js
  src/components/login/login.test.js
  src/components/mainMenu/mainMenu.js
  src/components/mainMenu/mainMenu.test.js
  src/components/register/register.js
  src/components/savedAccounts/savedAccounts.js
  src/components/savedAccounts/savedAccounts.test.js
  src/components/search/keyAction.js
  src/components/search/keyAction.test.js
  src/components/searchBar/index.js
  src/components/sendTo/index.js
  src/components/sendTo/sendTo.test.js
  src/components/transactions/transactionDetailView.js
  src/constants/routes.js
  src/utils/externalLinks.test.js
  src/utils/routes.js
Labels: :eye: pending review

#556 Make logo direct to dashboard - Closes #492
  src/components/mainMenu/mainMenu.js
Labels: :eye: pending review

#557 Improve account switcher wording - Closes #488
  i18n/locales/en/common.json
  src/components/savedAccounts/savedAccounts.css
  src/components/savedAccounts/savedAccounts.js
Labels: :white_check_mark: ready

#548 Make address in header copyable - Closes #468
  src/components/header/header.css
  src/components/header/header.js
  src/components/singleTransaction/index.js
  test/e2e/explorer.feature
  test/e2e/step_definitions/explorer.step.js
  test/integration/transactionID.test.js
Labels: :eye: pending review

#458 Improve account switcher e2e tests - Closes #541
  test/e2e/savedAccounts.feature
Labels: :eye: pending review

#517 Add account initialization - Closes #284
  i18n/locales/en/common.json
  package.json
  src/components/accountInitialization/accountInit.css
  src/components/accountInitialization/index.js
  src/components/dashboard/index.js
  src/components/dashboard/index.test.js
  src/components/multiStep/index.js
  src/components/passphraseSteps/index.js
  src/components/send/index.js
  src/components/send/index.test.js
  src/components/sendReadable/send.js
  src/components/sendReadable/send.test.js
  src/components/sendReadable/sendReadable.css
  src/components/transactionDashboard/index.js
  src/store/middlewares/account.js
  src/store/middlewares/account.test.js
  src/utils/api/account.js
  src/utils/api/account.test.js
  test/constants/accounts.js
  test/e2e/send.feature
  test/e2e/step_definitions/generic.step.js
  test/integration/wallet.test.js
  test/utils/genericStepDefinition.js
Labels: :white_check_mark: ready

#523 Add LockID feature - Closes #496
  i18n/locales/en/common.json
  src/actions/account.js
  src/actions/account.test.js
  src/actions/savedAccounts.js
  src/actions/savedAccounts.test.js
  src/components/header/header.js
  src/components/header/index.js
  src/components/header/index.test.js
  src/components/savedAccounts/index.js
  src/components/savedAccounts/savedAccounts.css
  src/components/savedAccounts/savedAccounts.js
  src/components/savedAccounts/savedAccounts.test.js
  src/constants/actions.js
  src/store/middlewares/login.js
  src/store/middlewares/login.test.js
  src/store/reducers/savedAccounts.js
  src/store/reducers/savedAccounts.test.js
  test/integration/accountSwitch.test.js
  test/integration/login.test.js
Labels: :eye: pending review

#560 Remove duplicate styles - Closes #555
  src/components/accountInitialization/accountInit.css
  src/components/accountInitialization/index.js
  src/components/app/variables.css
  src/components/box/box.css
  src/components/dashboard/currencyGraph.css
  src/components/dashboard/currencyGraph.js
  src/components/dashboard/dashboard.css
  src/components/delegateList/delegateList.css
  src/components/login/login.css
  src/components/passphraseSteps/index.js
  src/components/passphraseSteps/passphraseSteps.css
  src/components/resultBox/resultBox.js
  src/components/sendReadable/sendReadable.css
  src/components/sendTo/sendTo.css
  src/components/sendWritable/send.js
  src/components/sendWritable/sendWritable.css
  src/components/singleTransaction/singleTransaction.css
  src/components/transactions/transactionRow.js
  src/components/transactions/transactions.css
  src/components/votesPreview/votesPreview.css
Labels: :white_check_mark: ready

#544 Misplaced delegate filters in s breakpoint - Closes #368
  src/components/delegateList/delegateList.css
Labels: :eye: pending review

#574 Fix stuck on loading screen on transaction details - Closes #565
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionRow.js
  src/components/transactions/transactions.js
  test/integration/accountTransactions.test.js
Labels: :building_construction: in progress

#547 Increase test coverage of ignored files above 80% Part 4 - Closes #536
  karma.conf.js
  src/components/delegateList/delegateList.test.js
  src/components/delegateList/index.test.js
  src/components/toaster/index.js
  src/components/toaster/index.test.js
  src/components/toaster/toaster.test.js
  src/components/transactions/index.test.js
Labels: :eye: pending review

#573 Make built app an artifact of Jenkins build - Closes #566
  Jenkinsfile
Labels: :eye: pending review

#580 Vertical scroll performance bug in chrome - Closes #549
  src/components/delegateList/delegateList.css
  src/components/delegateList/delegateList.js
  src/components/delegateList/votingRow.js
Labels: :eye: pending review

#554 Implement 2nd passphrase registration - Closes #68
  i18n/locales/en/common.json
  karma.conf.js
  src/actions/account.js
  src/components/app/index.js
  src/components/passphrase/ConfirmSecond/confirmSecond.css
  src/components/passphrase/ConfirmSecond/confirmSecond.js
  src/components/passphrase/ConfirmSecond/index.js
  src/components/passphrase/confirm/index.js
  src/components/passphrase/create/create.css
  src/components/passphrase/create/index.js
  src/components/passphrase/createSecond/index.js
  src/components/passphrase/createSecond/progressBar.css
  src/components/passphrase/safekeeping/index.js
  src/components/passphrase/safekeeping/index.test.js
  src/components/secondPassphrase/index.js
  src/components/secondPassphrase/index.test.js
  src/components/secondPassphrase/secondPassphrase.css
  src/components/secondPassphrase/secondPassphrase.js
  src/components/secondPassphrase/secondPassphrase.test.js
  src/components/setting/setting.css
  src/components/setting/setting.js
  src/constants/routes.js
Labels: :white_check_mark: ready

#576 Fix see all transactions - Closes #571
  src/components/dashboard/index.js
  test/e2e/transactions.feature
Labels: :white_check_mark: ready

#500 Integration test for register page - Closes #103
  src/components/passphrase/create/index.js
  src/components/register/index.js
  test/integration/login.test.js
  test/integration/register.test.js
  test/utils/genericStepDefinition.js
Labels: :eye: pending review

#578 Fix filters persist - Closes #531
  src/components/delegateList/delegateList.js
  src/components/delegateList/votingRow.js
  test/integration/voting.test.js
Labels: :eye: pending review

#562 Migrate account switcher to a page - Closes #530, #338
  i18n/locales/en/common.json
  src/components/accountVisual/index.js
  src/components/app/index.js
  src/components/app/variables.css
  src/components/dialog/dialog.js
  src/components/dialog/dialog.test.js
  src/components/dialog/dialogs.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/menuBar/menuBar.css
  src/components/relativeLink/index.js
  src/components/savedAccounts/index.js
  src/components/savedAccounts/modalTheme.css
  src/components/savedAccounts/savedAccounts.css
  src/components/savedAccounts/savedAccounts.js
  src/constants/routes.js
  src/utils/generateUniqueId.js
  src/utils/generateUniqueId.test.js
  src/utils/routes.js
  test/e2e/voting.feature
  test/integration/accountSwitch.test.js
Labels: :eye: pending review

#587 Hide ID after creation - Closes #474
  src/components/passphrase/create/index.js
Labels: :white_check_mark: ready

#598 Improve test coverage of second passphrase - Close #564
  karma.conf.js
  src/components/passphrase/ConfirmSecond/confirmSecond.js
  src/components/passphrase/ConfirmSecond/confirmSecond.test.js
  src/components/passphrase/ConfirmSecond/index.test.js
  src/components/passphrase/createSecond/index.test.js
  src/components/secondPassphrase/index.js
  src/components/secondPassphrase/index.test.js
Labels: :eye: pending review

#597 Setup @advanced tag for e2e test scenarios - Closes #559
  Jenkinsfile
  protractor.conf.js
  test/e2e/explorer.feature
  test/e2e/login.feature
  test/e2e/savedAccounts.feature
  test/e2e/send.feature
  test/e2e/voting.feature
Labels: :eye: pending review

#596 Fix "Account not found" error in Delegates - Closes #552
  src/components/delegateList/delegateList.js
  src/components/delegateList/delegateList.test.js
  src/components/delegateList/index.js
  src/components/voting/voting.test.js
  test/constants/accounts.js
  test/integration/wallet.test.js
Labels: :eye: pending review

#570 Increase test coverage - Closes #535
  i18n/locales/en/common.json
  karma.conf.js
  src/components/dialog/dialogs.js
  src/components/header/header.js
  src/components/login/index.test.js
  src/components/register/index.test.js
  src/components/register/register.test.js
  src/components/savedAccounts/modalTheme.css
  src/components/searchBar/index.test.js
  src/components/sendWritable/index.js
  src/components/sendWritable/index.test.js
  src/components/sendWritable/send.test.js
  src/components/sidechains/index.js
  src/components/sidechains/index.test.js
  src/components/transactions/transactionOverview.test.js
  src/components/voteDialog/index.js
  src/components/voteDialog/index.test.js
  src/components/voteDialog/voteAutocomplete.css
  src/components/voteDialog/voteAutocomplete.js
  src/components/voteDialog/voteAutocomplete.test.js
  src/components/voteDialog/voteDialog.css
  src/components/voteDialog/voteDialog.js
  src/components/voteDialog/voteDialog.test.js
  src/utils/api/delegate.js
  src/utils/api/delegate.test.js
  src/utils/voting.js
  test/e2e/voting.feature
Labels: :eye: pending review

#614 Fix undefined e2e tests not failing - Closes #607
  protractor.conf.js
Labels: :eye: pending review

#612 Increase coverage on failing modules - Closes #561
  karma.conf.js
  src/components/setting/setting.test.js
Labels: :eye: pending review

#616 Open all external links in default browser - Closes #532
  app/src/modules/win.js
Labels: :eye: pending review

#610 Make address in account switcher copyable - Closes #594
  src/components/savedAccounts/savedAccounts.css
  src/components/savedAccounts/savedAccounts.js
Labels: :eye: pending review

#620 Apply electron security patch #611
  README.md
  package.json
Labels: :eye: pending review

#615 Direct dashboard transaction row to tx details
  src/components/accountTransactions/index.js
  src/components/accountTransactions/index.test.js
  src/components/dashboard/index.js
  src/components/dashboard/index.test.js
  src/components/transactions/index.test.js
  src/components/transactions/transactionDetailView.js
  src/components/transactions/transactionDetailView.test.js
  src/components/transactions/transactionList.js
  src/components/transactions/transactionOverview.js
  src/components/transactions/transactionRow.js
  src/components/transactions/transactionRow.test.js
  test/integration/accountTransactions.test.js
Labels: :eye: pending review

#606 Enable second passphrase registration e2e test - Closes #602
  Jenkinsfile
  package.json
  protractor.conf.js
  src/components/passphrase/ConfirmSecond/confirmSecond.js
  src/components/secondPassphrase/index.js
  test/e2e/registerSecondPassphrase.feature
  test/e2e/step_definitions/generic.step.js
  test/e2e/step_definitions/secondPassphrase.step.js
Labels: :eye: pending review

#572 Implement onboarding - Closes #63
  i18n/locales/en/common.json
  karma.conf.js
  package.json
  src/components/app/global.css
  src/components/app/index.js
  src/components/header/header.js
  src/components/mainMenu/mainMenu.js
  src/components/onboarding/index.js
  src/components/onboarding/onboarding.css
  src/components/onboarding/steps.js
  src/components/setting/index.js
  src/components/setting/setting.css
  src/components/setting/setting.js
  src/components/setting/setting.test.js
  src/constants/breakpoints.js
  test/e2e/step_definitions/hooks.js
Labels: :eye: pending review

#627 Split SavedAccount into smaller components - subTask #513
  src/components/savedAccounts/accountCard.js
  src/components/savedAccounts/accountCard.test.js
  src/components/savedAccounts/addAccountCard.js
  src/components/savedAccounts/card.css
  src/components/savedAccounts/savedAccounts.css
  src/components/savedAccounts/savedAccounts.js
Labels: :eye: pending review

#631 Split Login into smaller components - subTask #513
  src/components/login/animations.css
  src/components/login/layout.css
  src/components/login/login.css
  src/components/login/login.js
  src/components/login/shapes.css
  src/components/login/signUp.css
  src/components/login/signUp.js
Labels: :eye: pending review

#630 Finalize second passphrase registration feature - Closes #626
  src/components/mainMenu/mainMenu.js
  src/components/setting/setting.js
  src/components/setting/setting.test.js
Labels: :eye: pending review

#567 Fix vote launch protocol - Closes #279
  app/src/main.js
  i18n/locales/en/common.json
  karma.conf.js
  src/components/delegateList/delegateList.js
  src/components/delegateSidebar/index.js
  src/components/dialog/dialogs.js
  src/components/savedAccounts/modalTheme.css
  src/components/search/index.test.js
  src/components/setting/setting.test.js
  src/components/transactions/index.test.js
  src/components/voteUrlProcessor/voteUrlProcessor.js
  src/components/voteUrlProcessor/voteUrlProcessor.test.js
  src/components/votesPreview/votesPreview.test.js
  src/store/middlewares/account.test.js
  test/e2e/voting.feature
Labels: :eye: pending review

#603 Add new account component design - Closes #553
  i18n/locales/en/common.json
  src/components/copyToClipboard/index.js
  src/components/copyToClipboard/index.test.js
  src/components/header/countDownTemplate.js
  src/components/header/countDownTemplate.test.js
  src/components/header/customCountDown.css
  src/components/header/customCountDown.js
  src/components/header/customCountDown.test.js
  src/components/header/header.css
  src/components/header/header.js
  src/components/header/header.test.js
  src/components/header/index.js
Labels: :eye: pending review

#634 Automate Linux desktop build in Jenkins - Closes #609
  Jenkinsfile
  package.json
Labels: :eye: pending review

#629 Write e2e tests for onboarding - Closes #589
  src/components/onboarding/index.js
  src/components/setting/setting.js
  test/e2e/onboarding.feature
  test/e2e/step_definitions/hooks.js
Labels: :eye: pending review

#636 Split delegateList css into smaller files - subTask #513
  src/components/delegateList/delegateList.css
  src/components/delegateList/voteCheckbox.css
  src/components/delegateList/voteCheckbox.js
  src/components/delegateList/votingHeader.css
  src/components/delegateList/votingHeader.js
  src/components/delegateList/votingRow.js
  src/components/delegateList/votingRow.test.js
Labels: :eye: pending review

#623 Account switcher integration test fails randomly - Closes #583
  src/components/savedAccounts/accountCard.js
  src/components/savedAccounts/savedAccounts.test.js
  test/e2e/savedAccounts.feature
  test/integration/accountSwitch.test.js
  test/utils/genericStepDefinition.js
Labels: :eye: pending review
