Repository LiskHQ/lisk-desktop, pull requests merged in 2018-02, with the labels that each got.

#445 Add explorer e2e test - Closes #427
  package.json
  src/components/search/index.js
  src/components/searchBar/index.js
  src/components/sendTo/index.js
  test/e2e/explorer.feature
  test/e2e/step_definitions/generic.step.js
Labels: ready

#479 Fix a rendering issue in delegateList-Safari - Closes #472
  src/components/delegateList/delegateList.css
Labels: pending review

#482 Add unit tests to uncovered utilities - Closes #23
  i18n/locales/en/common.json
  karma.conf.js
  src/store/middlewares/socket.js
  src/store/middlewares/socket.test.js
  src/utils/externalLinks.js
  src/utils/externalLinks.test.js
  src/utils/ipcLocale.test.js
  src/utils/notification.test.js
  src/utils/socketShim.js
Labels: ready

#455 Style improvements in Register page - Closes #454
  src/components/passphrase/safekeeping/index.js
  src/components/passphrase/safekeeping/safekeeping.css
  src/index.html
Labels: pending review

#483 Improve test coverage of electron wrapper - Closes #473
  app/src/menu.test.js
  app/src/modules/autoUpdater.js
  app/src/modules/autoUpdater.test.js
  app/src/modules/localeHandler.test.js
  app/src/modules/win.test.js
  karma.conf.js
Labels: :white_check_mark: ready

#481 Fix 'npm run dist' on Linux - Closes #477
  app/assets/lisk.icns
  build/icon.icns
Labels: :eye: pending review

#480 Fix 'npm run build-prod' on Windows - Closes #478
  config/webpack.config.react.js
Labels: :eye: pending review

#476 Create an integration tests for voting component - Closes #290
  src/components/resultBox/resultBox.js
  test/e2e/voting.feature
  test/integration/voteDialog.test.js
  test/integration/voting.test.js
  test/utils/genericStepDefinition.js
  test/utils/mountHelpers.js
Labels: :eye: pending review

#486 Header disappears on small screens - Closes #459
  src/components/dashboard/index.js
  src/components/dashboard/styles.css
  src/components/send/index.js
Labels: :eye: pending review

#487 Use generic step helper in integration tests - Closes #485
  test/integration/accountSwitch.test.js
  test/integration/accountTransactions.test.js
  test/integration/steps.js
  test/integration/transactionID.test.js
  test/integration/voting.test.js
  test/integration/wallet.test.js
  test/utils/genericStepDefinition.js
Labels: :white_check_mark: ready

#494 Fix typo in create Lisk ID process - Closes #493
  src/components/passphrase/create/index.js
Labels: :eye: pending review
