Repository LiskHQ/lisk-desktop, pull requests merged in 2019-02, with the labels that each got.

#1698 Implement new Wallet Header and Buttons Styles - Closes #1634
  i18n/locales/en/common.json
  src/components/transactions/transactionsOverview.js
  src/components/transactions/walletTransactions/index.js
  src/components/transactions/walletTransactions/walletHeader.css
  src/components/transactions/walletTransactions/walletHeader.js
  src/components/transactions/walletTransactions/walletHeader.test.js
  src/components/transactions/walletTransactions/walletTransactions.js
  src/constants/routes.js
Labels: :white_check_mark: ready

#1708 Update top bar css breakpoints design from (S, M, L) to (M, L, XL) - Closes #1707
  src/components/autoSuggestV2/autoSuggest.css
  src/components/statusBar/statusBar.css
  src/components/topBar/menuItems.css
Labels: :white_check_mark: ready

#1717 Timer No passphrase check - Closes #1716
  src/components/statusBar/statusBar.js
Labels: :white_check_mark: ready

#1718 Fix HW: Page does not change after choosing account - Closes #1715
  src/components/hwWallet/ledgerLogin.js
Labels: :white_check_mark: ready

#1722 Fix delay before loading TXs to latest activity - Closes #1721
  src/components/hwWallet/hwWallet.js
  src/components/hwWallet/index.js
  src/components/hwWallet/ledgerLogin.js
Labels: :white_check_mark: ready

#1728 Implement load more button on wallet - Closes 1635
  i18n/locales/en/common.json
  src/actions/transactions.js
  src/components/app/variablesV2.css
  src/components/spinnerV2/spinnerV2.css
  src/components/spinnerV2/spinnerV2.js
  src/components/spinnerV2/spinnerV2.test.js
  src/components/statusBar/statusBar.css
  src/components/transactionsV2/transactionDetailV2.js
  src/components/transactionsV2/transactionDetailV2.test.js
  src/components/transactionsV2/transactionRowV2.css
  src/components/transactionsV2/transactionRowV2.js
  src/components/transactionsV2/transactionsHeaderV2.js
  src/components/transactionsV2/transactionsListV2.css
  src/components/transactionsV2/transactionsListV2.js
  src/components/transactionsV2/transactionsListV2.test.js
  src/components/transactionsV2/transactionsOverviewV2.js
  src/components/transactionsV2/transactionsOverviewV2.test.js
  src/components/transactionsV2/transactionsV2.css
  src/components/transactionsV2/walletTransactionsV2/index.js
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.js
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.test.js
Labels: :white_check_mark: ready

#1735 Remove export from mapDispatchToProps and mapStateToProps - Closes #1555
  src/components/feedbackForm/index.js
  src/components/toaster/index.js
  src/components/toaster/toaster.test.js
Labels: :eye: pending review

#1736 Replace old wallet with new wallet - Closes #1705
  src/assets/images/icons-v2/tx-2nd-passphrase.svg
  src/components/dashboard/index.js
  src/components/singleTransaction/index.js
  src/components/transactionDashboard/index.js
  src/components/transactions/walletTransactions/index.js
  src/components/transactions/walletTransactions/index.test.js
  src/components/transactions/walletTransactions/walletTransactions.js
  src/components/transactionsV2/transactionDetailV2.js
  src/components/transactionsV2/transactionDetailV2.test.js
  src/components/transactionsV2/transactionRowV2.js
  src/components/transactionsV2/transactionTypeV2.js
  src/components/transactionsV2/transactionsListV2.js
  src/components/transactionsV2/walletTransactionsV2/walletHeader.js
  src/components/transactionsV2/walletTransactionsV2/walletHeader.test.js
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.js
  src/constants/routes.js
  src/store/middlewares/account.js
  src/utils/api/transactions.js
  src/utils/api/transactions.test.js
  test/constants/urls.js
  test/cypress/e2e/activity.spec.js
  test/cypress/e2e/send.spec.js
  test/cypress/e2e/txDetails.spec.js
Labels: :white_check_mark: ready

#1734 Implement On-Boarding module in wallet - Closes #1669
  i18n/locales/en/common.json
  src/components/toolbox/banner/banner.css
  src/components/toolbox/banner/banner.js
  src/components/toolbox/banner/banner.test.js
  src/components/transactionsV2/walletTransactionsV2/index.js
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.css
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.js
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.test.js
  test/constants/selectors.js
  test/cypress/e2e/wallet.spec.js
Labels: :white_check_mark: ready

#1751 Reenable actions/transactions tests - Close #1750
  jest.config.js
  src/actions/transactions.test.js
Labels: :white_check_mark: ready

#1690 Autosuggest delegate fetching bug - Closes #1351
  src/components/autoSuggest/autoSuggest.css
  src/components/autoSuggest/index.js
  src/components/autoSuggest/index.test.js
  src/components/autoSuggest/resultsList.css
  src/components/autoSuggest/resultsList.js
  src/components/autoSuggest/searchResults.mock.js
  src/components/autoSuggestV2/index.js
  src/components/autoSuggestV2/index.test.js
  test/cypress/e2e/search.spec.js
Labels: :white_check_mark: ready

#1760 Implement animation of pending transaction on wallet - Closes #1744
  src/components/spinnerV2/spinnerV2.css
  src/components/spinnerV2/spinnerV2.js
  src/components/spinnerV2/spinnerV2.test.js
  src/components/transactionsV2/transactionRowV2.css
  src/components/transactionsV2/transactionRowV2.js
  src/components/transactionsV2/transactionRowV2.test.js
  src/components/transactionsV2/transactionTypeV2.js
  test/cypress/e2e/send.spec.js
  test/cypress/e2e/txDetails.spec.js
Labels: :white_check_mark: ready

#1762 Remove old components, tests - Closes #1642
  i18n/locales/en/common.json
  jest.config.js
  src/components/accountTransactions/accountTransactions.test.js
  src/components/app/index.js
  src/components/app/index.test.js
  src/components/autoSuggestV2/index.test.js
  src/components/converter/converter.test.js
  src/components/dashboard/currencyGraph.test.js
  src/components/errorBoundary/index.test.js
  src/components/header/customCountDown.js
  src/components/header/header.js
  src/components/header/header.test.js
  src/components/login/animations.css
  src/components/login/index.js
  src/components/login/index.test.js
  src/components/login/layout.css
  src/components/login/login.css
  src/components/login/login.js
  src/components/login/login.test.js
  src/components/login/shapes.css
  src/components/login/signUp.css
  src/components/login/signUp.js
  src/components/register/index.js
  src/components/register/register.css
  src/components/register/register.js
  src/components/register/register.test.js
  src/components/searchResult/index.test.js
  src/components/sendTo/followAccount.test.js
  src/components/sendTo/sendTo.test.js
  src/components/statusBar/statusBar.js
  src/components/statusBar/statusBar.test.js
  src/components/transactions/delegateStatistics.test.js
  src/components/transactions/explorerTransactions/index.test.js
  src/components/transactions/transactionDetailView/transactionDetailDateField.test.js
  src/components/transactions/transactionDetailView/transactionDetailView.test.js
  src/components/transactions/transactionsList.test.js
  src/components/transactions/transactionsOverview.test.js
  src/components/transactions/votedDelegates.test.js
  src/components/votesPreview/votesPreview.test.js
  src/components/voting/voting.test.js
  src/components/votingListView/votingListView.test.js
  src/constants/routes.js
  src/utils/externalLinks.test.js
  test/integration/accountTransactions.test.js
  test/integration/dashboard.test.js
  test/integration/login.test.js
  test/integration/register.test.js
  test/integration/registerDelegate.test.js
  test/integration/transactionID.test.js
  test/integration/voting.test.js
  test/integration/wallet.test.js
  test/unit-test-utils/applicationInit.js
  test/unit-test-utils/genericStepDefinition.js
  test/unit-test-utils/mountHelpers.js
Labels: :white_check_mark: ready

#1761 Use jest built-in matchers and mocking functions - Closes #1738
  .eslintrc
  docs/TEST_GUIDE.md
  package-lock.json
  package.json
  src/actions/transactions.test.js
  src/components/send/send.test.js
  test/cypress/e2e/account.spec.js
  test/cypress/support/index.js
Labels: :eye: pending review

#1771 Usage tracking doesn't work due to double slash in the url - Closes #1769
  src/constants/piwik.js
Labels: :white_check_mark: ready

#1772 Start server only once - Closes #1737
  app/package.json
  app/src/main.js
  app/src/modules/win.js
  app/src/modules/win.test.js
  package-lock.json
  package.json
Labels: :eye: pending review

#1766 Implement Request LSK as dropdown - Closes #1714
  i18n/locales/en/common.json
  src/components/converterV2/converterV2.css
  src/components/converterV2/converterV2.js
  src/components/converterV2/converterV2.test.js
  src/components/converterV2/index.js
  src/components/referenceInput/index.js
  src/components/request/index.js
  src/components/request/receive.css
  src/components/request/request.js
  src/components/request/request.test.js
  src/components/request/steps/confirmation/confirmation.js
  src/components/request/steps/confirmation/confirmation.test.js
  src/components/request/steps/confirmation/requestForm.css
  src/components/request/steps/confirmation/requestForm.js
  src/components/request/steps/confirmation/requestForm.test.js
  src/components/request/steps/description/description.js
  src/components/request/steps/description/description.test.js
  src/components/request/steps/howItWorks/howItWorks.js
  src/components/request/steps/howItWorks/howItWorks.test.js
  src/components/requestV2/requestV2.css
  src/components/requestV2/requestV2.js
  src/components/requestV2/requestV2.test.js
  src/components/toolbox/dropdownV2/dropdownV2.css
  src/components/toolbox/dropdownV2/dropdownV2.js
  src/components/toolbox/inputsV2/AutoresizeTextarea.js
  src/components/toolbox/inputsV2/AutoresizeTextarea.test.js
  src/components/toolbox/inputsV2/index.js
  src/components/toolbox/inputsV2/inputV2.css
  src/components/toolbox/inputsV2/inputV2.js
  src/components/toolbox/inputsV2/inputV2.test.js
  src/components/toolbox/inputsV2/textareaV2.js
  src/components/toolbox/inputsV2/textareaV2.test.js
  src/components/transactions/transactionsOverview.js
  src/components/transactions/transactionsOverview.test.js
  src/components/transactionsV2/walletTransactionsV2/walletHeader.css
  src/components/transactionsV2/walletTransactionsV2/walletHeader.js
  src/components/transactionsV2/walletTransactionsV2/walletHeader.test.js
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.js
  src/constants/routes.js
  src/utils/inputValidator.js
  test/constants/selectors.js
  test/cypress/e2e/request.spec.js
  test/cypress/e2e/wallet.spec.js
Labels: :white_check_mark: ready

#1781 Fix linux maximum stack exception - Closes #1733
  Jenkinsfile
Labels: ready

#1783 Fix not prepopulating fields when using Lisk protocol if user is not logged in - Closes #1782
  package-lock.json
  package.json
  src/components/app/index.test.js
  src/components/customRoute/customRoute.js
  test/cypress/e2e/login.spec.js
  test/cypress/e2e/send.spec.js
  test/cypress/utils/loginUI.js
Labels: ready

#1788 Fix Auto-Logout not showing action dialogs - Closes #1784
  src/components/header/customCountDown.js
  test/cypress/e2e/account.spec.js
  test/cypress/e2e/delegates.spec.js
  test/cypress/e2e/txDetails.spec.js
Labels: ready

#1703 Implement message filters tag - Closes #1664
  .gitignore
  i18n/locales/en/common.json
  package-lock.json
  package.json
  src/actions/account.js
  src/actions/transactions.js
  src/components/toolbox/dropdownV2/dropdownV2.test.js
  src/components/transactionsV2/filterBar.css
  src/components/transactionsV2/filterBar.js
  src/components/transactionsV2/filterBar.test.js
  src/components/transactionsV2/filterButton.css
  src/components/transactionsV2/filterButton.js
  src/components/transactionsV2/filterButton.test.js
  src/components/transactionsV2/transactionsOverviewV2.js
  src/components/transactionsV2/transactionsOverviewV2.test.js
  src/components/transactionsV2/transactionsV2.css
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.js
  src/store/reducers/transactions.js
  src/utils/api/transactions.js
Labels: ready

#1787 Implement login with more than 12 words - Closes #1748
  i18n/locales/en/common.json
  jest.config.js
  package-lock.json
  package.json
  src/components/loginV2/loginV2.js
  src/components/passphraseInputV2/passphraseInputV2.js
  src/components/passphraseInputV2/passphraseInputV2.test.js
Labels: ready

#1786 Implement a terms of use page - Closes #1739
  i18n/locales/en/common.json
  src/components/app/index.test.js
  src/components/dashboard/dashboard.css
  src/components/help/help.css
  src/components/help/help.js
  src/components/loginV2/loginV2.js
  src/components/loginV2/loginV2.test.js
  src/components/splashscreen/index.js
  src/components/splashscreen/splashscreen.js
  src/components/splashscreen/splashscreen.test.js
  src/components/termsOfUse/index.js
  src/components/termsOfUse/termsOfUse.css
  src/components/termsOfUse/termsOfUse.js
  src/components/termsOfUse/termsOfUse.test.js
  src/constants/routes.js
  src/store/reducers/settings.js
  test/constants/selectors.js
  test/cypress/e2e/activity.spec.js
  test/cypress/e2e/help.spec.js
  test/cypress/e2e/splashscreen.spec.js
  test/cypress/support/commands.js
Labels: ready

#1793 Implement filtering transactions by amount - Closes #1665
  i18n/locales/en/common.json
  src/components/transactionsV2/filters/amountFieldGroup.js
  src/components/transactionsV2/filters/amountFieldGroup.test.js
  src/components/transactionsV2/filters/filterContainer.js
  src/components/transactionsV2/filters/messageFieldGroup.js
  src/components/transactionsV2/transactionsOverviewV2.js
  src/components/transactionsV2/walletTransactionsV2/walletTransactionsV2.js
  src/utils/api/transactions.js
Labels: ready

#1792 Implement transaction filters tags - Closes #1667
  i18n/locales/en/common.json
  src/actions/transactions.js
  src/components/transactionsV2/explorerTransactionsV2/explorerTransactionsV2.js
  src/components/transactionsV2/filters/filterBar.css
  src/components/transactionsV2/filters/filterBar.js
  src/components/transactionsV2/filters/filterBar.test.js
Labels: ready
