Repository LiskHQ/lisk-desktop, pull requests merged in 2020-11, with the labels that each got.

#3173 Fix amount styles in transaction list - Closes #3118
  src/components/screens/wallet/explorer.js
  src/components/screens/wallet/transactions/transactionRow.js
  src/components/shared/transactionAmount/index.js
Labels: type: bug

#3152 Fix send entire balance - Closes #3146
  i18n/locales/en/common.json
  src/components/screens/send/form/form.test.js
  src/components/screens/send/form/useAmountField.js
  src/components/screens/send/form/useTransactionFeeCalculation.js
  src/constants/transactions.js
  src/utils/validators.js
Labels: type: bug

#3186 Improve dynamic fee e2e test - Closes #3150
  src/utils/api/lsk/account.js
  test/constants/selectors.js
  test/cypress/features/common/common.js
  test/cypress/features/delegateReg.feature
  test/cypress/features/send.feature
Labels: type: test

#3195 Adapt launch protocol handling - Closes #3194
  src/utils/externalLinks.js
  src/utils/externalLinks.test.js
Labels: type: bug

#3191 Fetch base fees from service - Closes #3081
  src/components/screens/lockedBalance/lockedBalance/index.js
  src/components/screens/registerDelegate/registerDelegate.test.js
  src/components/screens/registerDelegate/selectNameAndFee/selectNameAndFee.js
  src/components/screens/send/form/form.test.js
  src/components/screens/send/form/formLsk.js
  src/components/screens/send/form/useTransactionPriority.js
  src/components/screens/send/index.test.js
  src/components/screens/votingQueue/editor/editor.js
  src/components/shared/transactionPriority/transactionPriority.css
  src/components/shared/transactionPriority/transactionPriority.js
  src/components/shared/transactionPriority/transactionPriority.test.js
  src/utils/api/lsk/liskService.js
  src/utils/api/lsk/transactions.js
  src/utils/api/lsk/transactions.test.js
  src/utils/api/transactions.js
  test/constants/selectors.js
  test/cypress/features/common/common.js
  test/cypress/features/delegateReg.feature
  test/cypress/features/send.feature
  test/cypress/features/voting.feature
Labels: type: refactoring
